"""Step 6 — the committed, reviewable record of every run.

Shape decided 2026-07-23: a **landing page** carrying one line per run, linking to
a **per-run detail page**. Cadence decided in the same pass: the landing row is
written every run, but a detail page only when the run has something to say.

A "ran, all clean" detail page carries nothing, and the stated purpose of this
step is improving the process — but dropping the row too would lose the evidence
that the process runs at all, which is the more useful of the two signals.

Detail pages carry `[[wikilinks]]` so a graphify markdown ingest turns this log
into graph edges, making the process itself queryable alongside everything else.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from kb_setup.currency.decide import Verdict
    from kb_setup.currency.issues import Observation
    from kb_setup.currency.sync import SyncStatus
    from kb_setup.currency.upstream import UpstreamStatus

REPORT_DIR = Path("docs") / "currency"
RUNS_DIR = "runs"
LANDING = "README.md"

_TABLE_HEADER = "| run | tool | verdict | detail |"
_TABLE_RULE = "|---|---|---|---|"

_LANDING_PREAMBLE = """# Tool currency log

Every run of the tool-currency workflow appends a row here. A run that found
something also writes a detail page; a clean run is the row alone — deliberately,
so this table stays readable while still proving the process ran.

Generated by `kb-setup currency` (the shared engine). Do not hand-edit rows.
"""

_NOTES_EXCERPT_CHARS = 1200


@dataclass(frozen=True)
class RunRecord:
    """Everything one run of the workflow produced, ready to render."""

    tool: str
    sync: SyncStatus
    upstream: UpstreamStatus
    observations: tuple[Observation, ...]
    moved: tuple[Observation, ...]
    verdict: Verdict
    answers: tuple[tuple[str, str], ...] = ()

    @property
    def has_content(self) -> bool:
        """Whether this run earns a detail page."""
        return bool(
            self.sync.drifted
            or self.verdict.has_upgrade
            or self.moved
            or self.verdict.ambiguities
            or self.answers
            # A step-4 lookup that FAILED is content: without this, a run where
            # every tracked issue errored is indistinguishable from a clean one.
            or any(o.error for o in self.observations)
        )


def _cell(value: object) -> str:
    """Escape a value for a markdown table cell.

    A single `|` anywhere in a cell silently splits it into two columns and
    corrupts the whole table — and these cells carry upstream-controlled text
    (issue titles, error strings, paths). Newlines do the same to the row.

    Whitespace is COLLAPSED, not merely newline-substituted. Replacing each single
    newline with a space turned a paragraph break in a multi-line watch note into two
    consecutive spaces, which is rumdl MD064 — so a `currency.toml` note written
    in ordinary paragraphs produced a report that failed `mise run lint`. Any run
    of whitespace is meaningless inside a one-line cell anyway.
    """
    return _oneline(str(value).replace("|", "\\|"))


def _oneline(value: str | None) -> str:
    """Collapse any whitespace run to one space — safe inside a cell or a list item.

    Shared by `_cell` and `_ambiguity_section` because both embed multi-line
    foreign text (watch notes, upstream marker text) into single-line markdown
    constructs, and both produced rumdl MD064 on real content.

    `None` maps to `""` rather than raising: an unanswered gate's answer is None,
    which is the NORMAL state of a freshly written report, and no test covered
    rendering one — so a partial version of this function crashed the whole run
    on the commonest input it has.
    """
    return re.sub(r"\s+", " ", value).strip() if value else ""


def _slug(when: datetime, tool: str) -> str:
    return f"{when.date().isoformat()}-{tool}"


def _unique_detail_path(runs_dir: Path, when: datetime, tool: str) -> Path:
    base = _slug(when, tool)
    candidate = runs_dir / f"{base}.md"
    counter = 2
    while candidate.exists():
        candidate = runs_dir / f"{base}-{counter}.md"
        counter += 1
    return candidate


def _findings_table(sync: SyncStatus) -> str:
    rows = [
        "| check | status | detail |",
        "|---|---|---|",
        *(f"| {_cell(f.check)} | {_cell(f.status)} | {_cell(f.detail)} |" for f in sync.findings),
    ]
    return "\n".join(rows)


def _watch_table(observations: tuple[Observation, ...], moved: tuple[Observation, ...]) -> str:
    if not observations:
        return "_No watch items configured for this tool._"
    moved_keys = {o.key for o in moved}
    rows = [
        "| item | state | updated | comments | moved? |",
        "|---|---|---|---|---|",
    ]
    for o in observations:
        state = o.error or o.state or "?"
        rows.append(
            f"| {_cell(o.key)} | {_cell(state)} | {_cell(o.updated_at or '—')} | "
            f"{o.comments} | {'**yes**' if o.key in moved_keys else 'no'} |"
        )
    return "\n".join(rows)


def _ambiguity_section(verdict: Verdict, answers: tuple[tuple[str, str], ...]) -> str:
    if not verdict.ambiguities:
        return "_No residual ambiguity — nothing needed a human decision._"
    recorded = dict(answers)
    blocks: list[str] = []
    for a in verdict.ambiguities:
        answer = recorded.get(a.gate) or recorded.get(a.question)
        blocks.append(
            f"### Gate: {a.gate}\n\n"
            f"**{a.question}**\n\n"
            # `_oneline`, for the same reason `_cell` collapses whitespace: these
            # carry `currency.toml` watch notes and upstream marker text, and a
            # paragraph break inside a LIST ITEM becomes two consecutive spaces —
            # rumdl MD064, on content that is not ours to reformat.
            f"- Detail: {_oneline(a.detail)}\n"
            f"- Recommended: {_oneline(a.recommendation) or '—'}\n"
            f"- **Answer:** {_oneline(answer) or '_not yet answered_'}\n"
        )
    # rstrip: the template already supplies the blank line before the next
    # heading. Without this the generator emits a double blank line and every
    # run fails `mise run lint` (rumdl MD012) — a report generator that cannot
    # pass the repo's own gate is a report generator nobody will keep running.
    return "\n".join(blocks).rstrip()


def _reachable_line(upstream: UpstreamStatus) -> str:
    """Whether upstream was read — and, crucially, how COMPLETELY it was read.

    `reachable` and `error` are not opposites here. `probe()` returns
    `reachable=True` with `error` set for a PARTIAL read: PyPI answered, but a
    GitHub release lookup failed. Rendering that as a bare "yes" published a
    clean bill of health over a real `gh api ... exited 1`, which is the same
    absence-of-evidence shape this engine exists to refuse.
    """
    if not upstream.tracked:
        return "n/a — presence-tracked, no upstream version to chase"
    if not upstream.reachable:
        return f"**no** — {upstream.error}"
    if upstream.error:
        return f"partially — the version source answered, but: {upstream.error}"
    return "yes"


def _release_line(record: RunRecord) -> str:
    """How to describe the GitHub release, distinguishing 'skipped' from 'missing'.

    Release notes are only fetched when an upgrade exists, so "none found" would
    be a false claim on an already-current run — the report must not assert an
    absence it never went looking for.
    """
    if record.upstream.github_tag:
        return record.upstream.github_tag
    if not record.verdict.has_upgrade:
        return "not fetched — already on the latest version"
    return f"none found{f' ({record.upstream.error})' if record.upstream.error else ''}"


def _feature_section(verdict: Verdict) -> str:
    """The 'should we adopt this?' list — step 3's advisory half.

    Rendered only when the notes announced something feature-shaped, so a routine
    patch does not grow an empty heading. These never gated the bump; they are
    here for a human to skim and decide whether a new capability is worth a config
    change.
    """
    if verdict.features_unreadable:
        # NOT the same as "no features", and rendering nothing here is what let a
        # whole release go unread. Say that the scan could not parse the body, so
        # the reader knows the silence is ours and not upstream's.
        return (
            "### Features to consider adopting\n\n"
            "_**Could not tell.** The release notes are non-empty but match no "
            "changelog format this scan understands (no `Added`/`Highlights` "
            "section, no `feat:` prefixes, no adoption phrases), so this is "
            "**not** a report of zero features — read the notes by hand._"
        )
    if not verdict.feature_review:
        return ""
    lines = "\n".join(f"- {item}" for item in verdict.feature_review)
    dropped = (
        f"\n\n_{verdict.features_dropped} further feature line(s) were cut by the "
        "display cap — read the full notes if you are deciding on adoption._"
        if verdict.features_dropped
        else ""
    )
    return (
        "### Features to consider adopting\n\n"
        "_Advisory — these did not block the bump. Skim for a new capability "
        "worth a config change._\n\n"
        f"{lines}{dropped}"
    )


def _notes_excerpt(raw: str) -> str:
    """The release notes, FENCED so upstream's markdown cannot break our own gate.

    These are foreign text quoted for the record, and embedding them raw made this
    repo's markdown lint a hostage to upstream's formatting choices: mise
    v2026.7.16 writes `## Highlights` immediately followed by a list item, which
    is rumdl MD032, so `mise run lint` failed on a file the engine had just
    generated — unfixable here, because the content is not ours to reformat.
    Fencing also stops upstream's `##` headings from inverting this page's own
    heading structure.

    The fence is longer than the longest backtick run inside, because release notes
    routinely contain fenced examples of their own (7.16 embeds a ```toml block); a
    fixed three-backtick fence would be closed early by the first one and spill the
    rest of the notes back into the document as live markdown.
    """
    notes = raw.strip()
    if not notes:
        return ""
    truncated = len(notes) > _NOTES_EXCERPT_CHARS
    body = notes[:_NOTES_EXCERPT_CHARS] + ("\n\n… (truncated)" if truncated else "")
    longest = max((len(run) for run in re.findall(r"`+", body)), default=0)
    fence = "`" * max(3, longest + 1)
    return f"{fence}text\n{body}\n{fence}"


def render_detail(record: RunRecord, when: datetime) -> str:
    """The full per-run detail page."""
    v = record.verdict
    excerpt = _notes_excerpt(record.upstream.notes)
    gates = (
        "\n".join(f"- ✅ {g}" for g in v.gates_passed)
        if v.gates_passed
        else "_No gate was evaluated (no upgrade pending, or upstream unreadable)._"
    )

    body = f"""# Currency run — {record.tool} — {when.isoformat(timespec="seconds")}

**Verdict:** {v.summary()}

Related: [[tool-currency-log]] · [[{record.tool}]]

## Step 1 — in sync?

Pinned `{record.sync.pinned or "—"}` · resolved `{record.sync.resolved or "—"}`

{_findings_table(record.sync)}

## Steps 2-3 — upstream

- Latest ({record.upstream.source}): `{record.upstream.latest or "unknown"}`
- GitHub release: `{_release_line(record)}`
- Reachable: {_reachable_line(record.upstream)}

### Release notes

{excerpt or "_No release notes retrieved._"}

{_feature_section(v)}

## Step 4 — tracked issues and watch items

{_watch_table(record.observations, record.moved)}

## Step 5 — decision

Gates passed:

{gates}

{_ambiguity_section(v, record.answers)}

## Step 6 — process note

This page is the immutable record of ONE run — a later run writes its own new
page rather than rewriting this one. Annotate it freely with review notes;
nothing here is regenerated.
"""
    # Optional sections (feature review, ambiguities) leave a blank when absent,
    # which stacks into the MD012 consecutive-blank-line violation that fails the
    # repo's own markdown gate. Collapse any run of blank lines to one, so an
    # empty section never makes a report the engine cannot commit.
    return re.sub(r"\n{3,}", "\n\n", body)


def _ensure_landing(path: Path) -> list[str]:
    if path.exists():
        return path.read_text(encoding="utf-8").splitlines()
    return [*_LANDING_PREAMBLE.splitlines(), "", _TABLE_HEADER, _TABLE_RULE]


def append_row(report_root: Path, *, when: datetime, verdict: Verdict, detail: Path | None) -> Path:
    """Append this run's one-line row to the landing page, newest first."""
    path = report_root / LANDING
    lines = _ensure_landing(path)
    link = f"[{detail.stem}]({RUNS_DIR}/{detail.name})" if detail else "—"
    stamp = when.isoformat(timespec="minutes")
    row = f"| {stamp} | {_cell(verdict.tool)} | {_cell(verdict.summary())} | {link} |"

    if _TABLE_RULE in lines:
        idx = lines.index(_TABLE_RULE) + 1
    else:  # a hand-mangled landing page: rebuild the table rather than lose the row
        lines += ["", _TABLE_HEADER, _TABLE_RULE]
        idx = len(lines)
    lines.insert(idx, row)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return path


def write_run(
    repo_root: Path, record: RunRecord, *, now: datetime | None = None
) -> tuple[Path, Path | None]:
    """Write the landing row (always) and the detail page (only when earned).

    Returns `(landing_path, detail_path_or_None)`.
    """
    when = now or datetime.now(UTC)
    report_root = repo_root / REPORT_DIR

    detail: Path | None = None
    if record.has_content:
        runs_dir = report_root / RUNS_DIR
        runs_dir.mkdir(parents=True, exist_ok=True)
        detail = _unique_detail_path(runs_dir, when, record.tool)
        detail.write_text(render_detail(record, when), encoding="utf-8")

    landing = append_row(report_root, when=when, verdict=record.verdict, detail=detail)
    return landing, detail
