"""Step 6 — the committed, reviewable record of every run.

Shape decided 2026-07-23: a **landing page** carrying one line per run, linking to
a **per-run detail page**. Cadence decided in the same pass: the landing row is
written every run, but a detail page only when the run has something to say.

A "ran, all clean" detail page carries nothing, and the stated purpose of this
step is improving the process — but dropping the row too would lose the evidence
that the process runs at all, which is the more useful of the two signals.

Detail pages carry `[[wikilinks]]` so a graphify markdown ingest turns this log
into graph edges, making the process itself queryable alongside everything else.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from kb_setup.currency.decide import Verdict
    from kb_setup.currency.issues import Observation
    from kb_setup.currency.sync import SyncStatus
    from kb_setup.currency.upstream import UpstreamStatus

REPORT_DIR = Path("docs") / "currency"
RUNS_DIR = "runs"
LANDING = "README.md"

_TABLE_HEADER = "| run | tool | verdict | detail |"
_TABLE_RULE = "|---|---|---|---|"

_LANDING_PREAMBLE = """# Tool currency log

Every run of the tool-currency workflow appends a row here. A run that found
something also writes a detail page; a clean run is the row alone — deliberately,
so this table stays readable while still proving the process ran.

Generated by `kb-setup currency` (the shared engine). Do not hand-edit rows.
"""

_NOTES_EXCERPT_CHARS = 1200


@dataclass(frozen=True)
class RunRecord:
    """Everything one run of the workflow produced, ready to render."""

    tool: str
    sync: SyncStatus
    upstream: UpstreamStatus
    observations: tuple[Observation, ...]
    moved: tuple[Observation, ...]
    verdict: Verdict
    answers: tuple[tuple[str, str], ...] = ()

    @property
    def has_content(self) -> bool:
        """Whether this run earns a detail page."""
        return bool(
            self.sync.drifted
            or self.verdict.has_upgrade
            or self.moved
            or self.verdict.ambiguities
            or self.answers
        )


def _slug(when: datetime, tool: str) -> str:
    return f"{when.date().isoformat()}-{tool}"


def _unique_detail_path(runs_dir: Path, when: datetime, tool: str) -> Path:
    base = _slug(when, tool)
    candidate = runs_dir / f"{base}.md"
    counter = 2
    while candidate.exists():
        candidate = runs_dir / f"{base}-{counter}.md"
        counter += 1
    return candidate


def _findings_table(sync: SyncStatus) -> str:
    rows = [
        "| check | status | detail |",
        "|---|---|---|",
        *(f"| {f.check} | {f.status} | {f.detail} |" for f in sync.findings),
    ]
    return "\n".join(rows)


def _watch_table(observations: tuple[Observation, ...], moved: tuple[Observation, ...]) -> str:
    if not observations:
        return "_No watch items configured for this tool._"
    moved_keys = {o.key for o in moved}
    rows = [
        "| item | state | updated | comments | moved? |",
        "|---|---|---|---|---|",
    ]
    for o in observations:
        state = o.error or o.state or "?"
        rows.append(
            f"| {o.key} | {state} | {o.updated_at or '—'} | {o.comments} | "
            f"{'**yes**' if o.key in moved_keys else 'no'} |"
        )
    return "\n".join(rows)


def _ambiguity_section(verdict: Verdict, answers: tuple[tuple[str, str], ...]) -> str:
    if not verdict.ambiguities:
        return "_No residual ambiguity — nothing needed a human decision._"
    recorded = dict(answers)
    blocks: list[str] = []
    for a in verdict.ambiguities:
        answer = recorded.get(a.gate) or recorded.get(a.question)
        blocks.append(
            f"### Gate: {a.gate}\n\n"
            f"**{a.question}**\n\n"
            f"- Detail: {a.detail}\n"
            f"- Recommended: {a.recommendation or '—'}\n"
            f"- **Answer:** {answer or '_not yet answered_'}\n"
        )
    # rstrip: the template already supplies the blank line before the next
    # heading. Without this the generator emits a double blank line and every
    # run fails `mise run lint` (rumdl MD012) — a report generator that cannot
    # pass the repo's own gate is a report generator nobody will keep running.
    return "\n".join(blocks).rstrip()


def _release_line(record: RunRecord) -> str:
    """How to describe the GitHub release, distinguishing 'skipped' from 'missing'.

    Release notes are only fetched when an upgrade exists, so "none found" would
    be a false claim on an already-current run — the report must not assert an
    absence it never went looking for.
    """
    if record.upstream.github_tag:
        return record.upstream.github_tag
    if not record.verdict.has_upgrade:
        return "not fetched — already on the latest version"
    return f"none found{f' ({record.upstream.error})' if record.upstream.error else ''}"


def render_detail(record: RunRecord, when: datetime) -> str:
    """The full per-run detail page."""
    v = record.verdict
    notes = record.upstream.notes.strip()
    truncated = len(notes) > _NOTES_EXCERPT_CHARS
    excerpt = notes[:_NOTES_EXCERPT_CHARS] + ("\n\n… (truncated)" if truncated else "")
    gates = (
        "\n".join(f"- ✅ {g}" for g in v.gates_passed)
        if v.gates_passed
        else "_No gate was evaluated (no upgrade pending, or upstream unreadable)._"
    )

    return f"""# Currency run — {record.tool} — {when.isoformat(timespec="seconds")}

**Verdict:** {v.summary()}

Related: [[tool-currency-log]] · [[{record.tool}]]

## Step 1 — in sync?

Pinned `{record.sync.pinned or "—"}` · resolved `{record.sync.resolved or "—"}`

{_findings_table(record.sync)}

## Steps 2-3 — upstream

- PyPI latest: `{record.upstream.pypi_latest or "unknown"}`
- GitHub release: `{_release_line(record)}`
- Reachable: {"yes" if record.upstream.reachable else f"**no** — {record.upstream.error}"}

### Release notes

{excerpt or "_No release notes retrieved._"}

## Step 4 — tracked issues and watch items

{_watch_table(record.observations, record.moved)}

## Step 5 — decision

Gates passed:

{gates}

{_ambiguity_section(v, record.answers)}

## Step 6 — process note

This page is the committed record of the run. Amend it by hand only to add
review notes; the generated sections above are rewritten by the next run.
"""


def _ensure_landing(path: Path) -> list[str]:
    if path.exists():
        return path.read_text(encoding="utf-8").splitlines()
    return [*_LANDING_PREAMBLE.splitlines(), "", _TABLE_HEADER, _TABLE_RULE]


def append_row(report_root: Path, *, when: datetime, verdict: Verdict, detail: Path | None) -> Path:
    """Append this run's one-line row to the landing page, newest first."""
    path = report_root / LANDING
    lines = _ensure_landing(path)
    link = f"[{detail.stem}]({RUNS_DIR}/{detail.name})" if detail else "—"
    stamp = when.isoformat(timespec="minutes")
    row = f"| {stamp} | {verdict.tool} | {verdict.summary()} | {link} |"

    if _TABLE_RULE in lines:
        idx = lines.index(_TABLE_RULE) + 1
    else:  # a hand-mangled landing page: rebuild the table rather than lose the row
        lines += ["", _TABLE_HEADER, _TABLE_RULE]
        idx = len(lines)
    lines.insert(idx, row)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return path


def write_run(
    repo_root: Path, record: RunRecord, *, now: datetime | None = None
) -> tuple[Path, Path | None]:
    """Write the landing row (always) and the detail page (only when earned).

    Returns `(landing_path, detail_path_or_None)`.
    """
    when = now or datetime.now(UTC)
    report_root = repo_root / REPORT_DIR

    detail: Path | None = None
    if record.has_content:
        runs_dir = report_root / RUNS_DIR
        runs_dir.mkdir(parents=True, exist_ok=True)
        detail = _unique_detail_path(runs_dir, when, record.tool)
        detail.write_text(render_detail(record, when), encoding="utf-8")

    landing = append_row(report_root, when=when, verdict=record.verdict, detail=detail)
    return landing, detail
