# Copyright (c) 2026 Raymond Manaloto
"""Build-time gates for Claude Code function-hook modules (#1026).

Function-hook runtime failures are silent and fail open, so the repository
checks the two classes the harness can establish before loading a plugin:
Claude Code validates the module's syntax and event names, while TypeScript
checks handler return shapes against declarations generated by `/plugin-types`.
The explicit typed-register assertion is the bridge between them; without it,
TypeScript accepts an ``any``-typed module and the second gate proves nothing.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Final, Protocol

from kb_setup import claude_types

if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence

FIXTURE_ROOT = "tests/fixtures/fnhook"

_TYPE_FILENAMES = ("claude-code.d.ts", "claude-code-mcp.d.ts")

# The mise tool names whose pins back the two gate binaries. `mise exec -- <bin>`
# is NOT enough: with no tool named it resolves the bare SHIM, and mise then has
# no version to map it to. Measured on a GitHub runner 2026-09-12 — both tools
# installed fine and the gate still died on
# `mise ERROR No version is set for shim: claude`. It passed locally because a
# shim resolves on this Mac, so the host is not a control arm for CI.
#
# The version is READ FROM `mise.toml` rather than written here, so a pin bump
# cannot leave the invocation naming a stale version.
# The caller supplies its repository root. Tool specs come from the consumer's
# mise.toml, never from the installed package location.


#: The Claude Code binary, invoked straight off `PATH` — deliberately NOT
#: through `mise exec`.
#:
#: The `github:anthropics/claude-code` `[tools]` pin was removed in `6d1ae23`
#: so the native installer at `~/.local/bin/claude` owns PATH and self-updates
#: (grilling decision Q1; `currency.toml:29-39`). `mise exec <spec>` survived
#: that removal and became a trap: with no pin to activate, mise falls through
#: to an on-demand `@latest` install, which `MISE_LOCKED=1` refuses on a linux
#: runner. Measured on PR #1128 (run 35011570326):
#:
#:     mise ✗ github:anthropics/claude-code@2.1.272  failed: No lockfile URL
#:     found for github:anthropics/claude-code@2.1.272 on platform linux-x64
#:     (--locked mode)
#:
#: It passed on the development Mac throughout, because an on-demand install is
#: allowed there — the host was not a control arm for CI. CI now installs the
#: pinned version with Anthropic's own installer (`ci.yml`, the lint job), which
#: `MISE_LOCKED` does not govern, so the gate runs for real on both.
CLAUDE_BINARY = "claude"

#: `schemas/sources.toml`'s key for Claude Code. That file IS the pin for this
#: tool — there is no mise entry to read — so it is the single source CI's
#: installer and the vendored declarations both resolve from.
CLAUDE_SCHEMA_TOOL = "claude-code"

TSC_TOOL = "npm:typescript"


def claude_code_pin(repo_root: Path) -> str:
    """The Claude Code version `schemas/sources.toml` pins.

    Delegates to :func:`kb_setup.claude_types.load_pin` rather
    than re-reading the file, so this and the `schema-vendor pin` subcommand CI
    installs from cannot disagree about the same field.
    """
    return claude_types.load_pin(repo_root).version


def tool_spec(repo_root: Path, tool: str) -> str:
    """`<tool>@<version>` using the pin in `mise.toml`, so the two cannot drift.

    Claude Code is deliberately not resolvable here: it has no `[tools]` pin,
    and `validate_plugin` runs the binary off `PATH` instead. Passing its mise
    spec raises, which is what stops the removed wrapper being reinstated.
    """
    config = tomllib.loads((repo_root / "mise.toml").read_text(encoding="utf-8"))
    tools = config.get("tools", {})
    version = tools.get(tool)

    if not isinstance(version, str):
        message = (
            f"{tool} is not pinned as an exact version in mise.toml — the gate "
            f"cannot name a tool it has no pin for (found {version!r})"
        )
        raise TypeError(message)
    return f"{tool}@{version}"


_COMMAND_TIMEOUT_SECONDS = 120.0
_DEFAULT_MISE_STATE_DIR = Path(tempfile.mkdtemp(prefix="fnhook-mise-state-"))
#: Tools whose denial removes the session's only way to report or ask about the
#: denial. Not repair tools — neither executes anything — which is why
#: permitting them widens no capability.
ESCAPE_HATCH_TOOLS: Final = ("AskUserQuestion", "SendUserMessage")

#: A module that registers this event can return `deny`; no other classic event
#: can. Scoping by the EVENT rather than by the presence of a `deny` literal is
#: deliberate: a handler that only observes today can deny tomorrow without
#: re-registering, and a `deny` returned from a helper would drop out of a
#: literal-matching scope silently — passing the gate by becoming invisible to
#: it.
_PRE_TOOL_USE_RE = re.compile(r"""on\(\s*["']classic\.PreToolUse["']""")

#: `const NAME = new Set([...])` — the identifier is captured so the call-site
#: half can be bound to the same name the set half matched.
_TOOL_SET_RE = re.compile(r"const\s+(\w+)\s*=\s*new\s+Set\(\[(.*?)\]\)", re.DOTALL)

_TYPED_REGISTER_RE = re.compile(
    r"\bexport\s+const\s+register\s*:\s*Register\b",
)
_ENVIRONMENT_INTERFACE_NAMES = (
    b"BuiltinToolInputs",
    b"BuiltinToolResults",
)
_NORMALIZED_INTERFACE_BODY = b"    // Built-in tool inventory varies by generating session.\n"


@dataclass(frozen=True)
class GateInputs:
    """Consumer-owned paths and tool pin, independent of the installed package."""

    fixture_root: str = FIXTURE_ROOT
    type_filenames: tuple[str, ...] = _TYPE_FILENAMES
    tsc_tool: str = TSC_TOOL
    tsconfig: str = "tsconfig.json"


@dataclass(frozen=True)
class GateResult:
    """One gate invocation's observable result."""

    rc: int
    stdout: str = ""
    stderr: str = ""

    @property
    def ok(self) -> bool:
        """Whether the gate passed."""
        return self.rc == 0


class Runner(Protocol):
    """Injected subprocess boundary used by unit tests and production."""

    def __call__(
        self,
        command: list[str],
        *,
        cwd: Path,
        env: Mapping[str, str] | None = None,
        input_text: str | None = None,
    ) -> GateResult:
        """Run ``command`` and return its captured streams."""
        ...


def mise_child_env(state_dir: Path | None = None) -> dict[str, str]:
    """Return isolated mise state/log paths, sharing one temp root by default."""
    root = _DEFAULT_MISE_STATE_DIR if state_dir is None else state_dir
    root.mkdir(parents=True, exist_ok=True)
    return {
        "MISE_STATE_DIR": str(root),
        "MISE_LOG_FILE": str(root / "mise.log"),
    }


def default_runner(
    command: list[str],
    *,
    cwd: Path,
    env: Mapping[str, str] | None = None,
    input_text: str | None = None,
    mise_state_dir: Path | None = None,
) -> GateResult:
    """Run one bounded command; missing binaries and timeouts fail loudly."""
    child_env = os.environ.copy()
    if env is not None:
        child_env.update(env)
    if command and command[0] == "mise":
        child_env.update(mise_child_env(mise_state_dir))
    try:
        completed = subprocess.run(
            command,
            cwd=cwd,
            env=child_env,
            input=input_text,
            capture_output=True,
            text=True,
            check=False,
            timeout=_COMMAND_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired:
        return GateResult(rc=124, stderr="command timed out")
    except OSError as exc:
        return GateResult(rc=127, stderr=str(exc))
    return GateResult(
        rc=completed.returncode,
        stdout=completed.stdout,
        stderr=completed.stderr,
    )


def discover_plugin_dirs(
    repo_root: Path,
    *,
    include_fixtures: bool = False,
    fixture_root: str = FIXTURE_ROOT,
) -> list[Path]:
    """Return dirs containing both required Claude Code plugin manifests.

    The set is derived from the tree. Two things are excluded:
    :data:`FIXTURE_ROOT` from the production gate (a plugin elsewhere under
    ``tests/`` still counts), and any plugin inside a NESTED GIT CHECKOUT.

    The nested-checkout rule is not hypothetical. CI clones the sibling
    knowledge-base repo into `.rule-sync/` for the cross-repo rule gate, and
    that repo really does ship a function-hook plugin — `kb-settings-guard`,
    untyped. Discovery found it on a GitHub runner (2026-09-12) and the typed-
    module assertion correctly flagged it, failing this repo's gate over
    another repo's code. Both halves of that were working as designed; the
    scope was wrong.

    Excluding by "has its own `.git`" rather than by the name `.rule-sync`
    means any future sibling checkout is handled the day it appears, and the
    rule states the actual invariant: this gate governs THIS repo's modules.
    """
    fixture_path = (repo_root / fixture_root).resolve()
    root = repo_root.resolve()
    discovered: list[Path] = []
    for plugin_manifest in repo_root.rglob(".claude-plugin/plugin.json"):
        plugin_dir = plugin_manifest.parent.parent
        if not (plugin_dir / "hooks" / "hooks.json").is_file():
            continue
        resolved = plugin_dir.resolve()
        if not include_fixtures and resolved.is_relative_to(fixture_path):
            continue
        if _is_in_nested_checkout(resolved, root):
            continue
        ignored = subprocess.run(
            ["git", "check-ignore", "--quiet", str(plugin_manifest)],
            cwd=repo_root,
            capture_output=True,
            check=False,
            timeout=30,
        )
        if ignored.returncode == 0:
            continue
        discovered.append(plugin_dir)
    return sorted(discovered)


def _is_in_nested_checkout(plugin_dir: Path, repo_root: Path) -> bool:
    """Whether any directory between `plugin_dir` and `repo_root` owns a `.git`.

    `repo_root`'s own `.git` is deliberately not consulted — every path is
    inside it, so including it would exclude everything.
    """
    for parent in (plugin_dir, *plugin_dir.parents):
        if parent == repo_root:
            return False
        if not parent.is_relative_to(repo_root):
            return False
        if (parent / ".git").exists():
            return True
    return False


def validate_plugin(
    plugin_dir: Path,
    *,
    runner: Runner = default_runner,
) -> GateResult:
    """Run Claude Code's strict static validator for one complete plugin.

    `--strict` promotes warnings to errors, which is the mode Anthropic
    documents for CI use (`plugins-reference.md:506`). The binary comes off
    `PATH`; see :data:`CLAUDE_BINARY` for why it is not wrapped in `mise exec`.
    A missing binary is rc=127 from :func:`default_runner` and fails the gate —
    never a pass, per `.claude/rules/probes-need-a-control-arm.md`.
    """
    return runner(
        [
            CLAUDE_BINARY,
            "plugin",
            "validate",
            "--strict",
            str(plugin_dir),
        ],
        cwd=Path.cwd(),
    )


def _module_paths(dirs: Sequence[Path]) -> list[Path]:
    """Resolve every function-hook module declared by ``dirs``."""
    modules: set[Path] = set()
    for plugin_dir in dirs:
        hooks_manifest = plugin_dir / "hooks" / "hooks.json"
        try:
            payload = json.loads(hooks_manifest.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            msg = f"{hooks_manifest}: cannot read hooks manifest: {exc}"
            raise ValueError(msg) from exc
        declared = payload.get("modules") if isinstance(payload, dict) else None
        if not isinstance(declared, list) or not all(
            isinstance(item, str) and item for item in declared
        ):
            msg = f"{hooks_manifest}: modules must be a non-empty string list"
            raise ValueError(msg)
        for relative_path in declared:
            module = (hooks_manifest.parent / relative_path).resolve()
            if not module.is_file():
                msg = f"{hooks_manifest}: declared module does not exist: {relative_path}"
                raise ValueError(msg)
            modules.add(module)
    return sorted(modules)


def assert_modules_are_typed(dirs: list[Path]) -> GateResult:
    """Require every declared module to export ``register: Register``."""
    try:
        modules = _module_paths(dirs)
    except ValueError as exc:
        return GateResult(rc=1, stdout=f"{exc}\n")

    untyped = [
        module
        for module in modules
        if _TYPED_REGISTER_RE.search(module.read_text(encoding="utf-8")) is None
    ]
    if not untyped:
        return GateResult(rc=0)
    rendered = "\n".join(f"untyped function-hook module: {path}" for path in untyped)
    return GateResult(rc=1, stdout=f"{rendered}\n")


def assert_escape_hatch_permitted(dirs: list[Path]) -> GateResult:
    """Require every deny-capable module to permit the escape-hatch tools.

    Measured 2026-09-13: the ``install-doctor`` hook denied ``AskUserQuestion``
    and ``SendUserMessage`` while reporting a broken install, so three sessions
    in a row could see the finding and had no way to ask about it or report it.
    The fix had to be dictated as plain text and applied by hand. Its own
    contract names the rule it broke — "a gate you cannot talk your way out of
    does not protect the session, it ends it" — which is why this is a gate and
    not a comment.

    **Both halves are asserted, and the second is the load-bearing one.** A set
    naming both tools proves nothing on its own: a module can declare it and
    never consult it, and a membership-only check would stay green while the
    lockout came back. So the set's identifier is captured and required to
    appear in a ``.has(`` call in the same module. That is the call-site binding
    ``feedback_forbid_tokens_substring_fragile`` asks for, and it is the shape
    ``feedback_coarse_mutation_certifies_nothing`` records passing at rc=0 when
    only half a two-part change was reverted.

    Scope is the EVENT, not a ``deny`` literal — see :data:`_PRE_TOOL_USE_RE`.
    A module registering no blocking event is out of scope and needs no set.
    """
    try:
        modules = _module_paths(dirs)
    except ValueError as exc:
        return GateResult(rc=1, stdout=f"{exc}\n")

    problems: list[str] = []
    for module in modules:
        source = module.read_text(encoding="utf-8")
        if _PRE_TOOL_USE_RE.search(source) is None:
            continue
        permitting = [
            name
            for name, body in _TOOL_SET_RE.findall(source)
            if all(f'"{tool}"' in body for tool in ESCAPE_HATCH_TOOLS)
        ]
        if not permitting:
            problems.append(
                f"{module}: registers classic.PreToolUse but no Set permits "
                f"{', '.join(ESCAPE_HATCH_TOOLS)} — denying those leaves the "
                f"session no way to ask about the denial or report it"
            )
            continue
        if not any(re.search(rf"\b{re.escape(name)}\.has\s*\(", source) for name in permitting):
            problems.append(
                f"{module}: declares {', '.join(permitting)} naming the "
                f"escape-hatch tools but never consults it — a set nothing "
                f"reads permits nothing"
            )
    if not problems:
        return GateResult(rc=0)
    return GateResult(rc=1, stdout="\n".join(problems) + "\n")


def typecheck_modules(
    dirs: list[Path],
    *,
    runner: Runner = default_runner,
    repo_root: Path | None = None,
    inputs: GateInputs | None = None,
) -> GateResult:
    """Type-check Git-owned plugin hook sources and the pinned declarations.

    Include untracked, non-ignored helpers too, so the gate works before staging.
    An ignored declared module is an invalid input, not a reason to drop a gate.
    """
    repo_root = (repo_root or Path.cwd()).resolve()
    inputs = inputs or GateInputs()
    try:
        modules = _module_paths(dirs)
    except ValueError as exc:
        return GateResult(rc=1, stdout=f"{exc}\n")

    files = [repo_root / ".claude" / "types" / name for name in inputs.type_filenames]
    missing = [path for path in files if not path.is_file()]
    if missing:
        rendered = ", ".join(str(path) for path in missing)
        return GateResult(
            rc=1,
            stdout=f"missing function-hook declarations: {rendered}\n",
        )

    ownership = default_runner(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
        cwd=repo_root,
    )
    if not ownership.ok:
        return GateResult(
            rc=1,
            stdout=ownership.stdout,
            stderr=f"cannot select Git-owned function-hook inputs: {ownership.stderr}",
        )
    owned = {
        (repo_root / relative).resolve() for relative in ownership.stdout.split("\0") if relative
    }
    unowned = [path for path in [*files, *modules] if path.resolve() not in owned]
    if unowned:
        return GateResult(
            rc=1,
            stdout="function-hook inputs are ignored or outside the repository: "
            + ", ".join(str(path) for path in unowned)
            + "\n",
        )
    hook_dirs = [(plugin / "hooks").resolve() for plugin in dirs]
    helpers = {
        path
        for path in owned
        if path.suffix == ".ts"
        and path.is_file()
        and any(path.is_relative_to(directory) for directory in hook_dirs)
        and not _is_in_nested_checkout(path.parent, repo_root)
    }

    with tempfile.TemporaryDirectory(prefix="fnhook-tsc-") as temp_dir:
        project = Path(temp_dir) / "tsconfig.json"
        project.write_text(
            json.dumps(
                {
                    "extends": str(repo_root / inputs.tsconfig),
                    # `files` does not cancel an inherited `include`: without
                    # this override the consumer's globs also sweep its clones.
                    "include": [],
                    "files": [
                        str(path.resolve()) for path in [*files, *sorted(set(modules) | helpers)]
                    ],
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        return runner(
            [
                "mise",
                "exec",
                tool_spec(repo_root, inputs.tsc_tool),
                # The isolated MISE_STATE_DIR has no deps record, so mise's
                # `[deps.uv] auto` reads "stale (no previous state)" and runs
                # `uv sync` into stderr before tsc. Type-checking TS needs no
                # python deps; probed 2026-10-01: stderr 125 bytes -> 0.
                "--no-deps",
                "--",
                "tsc",
                "--noEmit",
                "--project",
                str(project),
            ],
            cwd=repo_root,
        )


def _generated_files(work_root: Path, names: tuple[str, ...] = _TYPE_FILENAMES) -> list[Path]:
    """The two files one successful `/plugin-types` invocation must write."""
    return [work_root / ".claude" / "types" / name for name in names]


def _missing_or_empty(paths: Sequence[Path]) -> list[Path]:
    """Return generated outputs that cannot be used as declarations."""
    return [path for path in paths if not path.is_file() or path.stat().st_size == 0]


def normalize_claude_code_declarations(source: bytes) -> bytes:
    """Replace only the two environment-dependent built-in-tool bodies.

    ``/plugin-types`` writes the generating session's available tools into two
    declaration-merging interfaces. The plugin API before and after them is
    stable and remains byte-sensitive. Requiring exactly one generated form of
    each interface makes a generator-format change fail closed.
    """
    normalized = source
    for name in _ENVIRONMENT_INTERFACE_NAMES:
        opening = b"  interface " + name + b" {\n"
        if normalized.count(opening) != 1:
            msg = f"expected exactly one generated {name.decode()} interface"
            raise ValueError(msg)
        body_start = normalized.index(opening) + len(opening)
        closing = b"\n  }\n}"
        body_end = normalized.find(closing, body_start)
        if body_end < 0:
            msg = f"generated {name.decode()} interface has no closing boundary"
            raise ValueError(msg)
        normalized = (
            normalized[:body_start] + _NORMALIZED_INTERFACE_BODY + normalized[body_end + 1 :]
        )
    return normalized


def drift_comparable_files(repo_root: Path) -> tuple[Path, ...]:
    """The declarations whose drift is meaningful to compare.

    `claude-code-mcp.d.ts` is EXCLUDED. It is not merely session-flavoured
    like the builtin-tool interfaces — it is per-session in its entirety, and
    its own header says so: with nothing connected it reports "no MCP tools
    are connected, so it is empty (every mcp__* tool stays loosely typed)",
    while a session with servers attached reports "170 MCP tools from 12
    servers" (both measured 2026-09-12, same machine, minutes apart). There is
    no stable subset to normalize down to, and nothing the type gate binds
    lives in it, so comparing it can only produce false drift.

    `claude-code.d.ts` IS compared, after normalization — that file carries the
    plugin API the gate actually consumes, and its normalizer has a control arm
    asserting an API-surface mutation is still detected.
    """
    return tuple(path for path in _generated_files(repo_root) if path.name != _TYPE_FILENAMES[1])


def _comparable_declaration_bytes(path: Path) -> bytes:
    """Read one declaration, normalizing the session-dependent regions away."""
    source = path.read_bytes()
    if path.name == _TYPE_FILENAMES[0]:
        return normalize_claude_code_declarations(source)
    return source


def _check_types_current(
    repo_root: Path, *, runner: Runner, inputs: GateInputs | None = None
) -> GateResult:
    """Verify vendored declarations exist, are non-empty, and pass type-checking.

    Claude Code's type declarations are now vendored from the upstream repository
    and refreshed via `mise run claude-types-refresh` (CI: schema-refresh job in
    refresh.yml), not generated locally with `/plugin-types`. This removes the
    hard dependency on a local Claude Code installation for the lint gate.

    This function verifies two things:
    1. The vendored file exists and is non-empty
    2. The sha256 recorded in schemas/sources.toml matches the file on disk

    Type-checking is NOT done here - `typecheck_modules()` owns it. The
    docstring claimed otherwise until 2026-09-15; the body always delegated.

    If any check fails, the gate returns non-zero. Absence must never read as
    "nothing to check" — the normalization function is retained because the
    environment-dependent built-in-tool interfaces still differ between machines,
    and drift detection still applies when comparing to upstream.
    """
    # Kept for signature compatibility with the other gate helpers; this one
    # reads files and hashes rather than shelling out. `del` satisfies ruff's
    # ARG001 without an inline suppression, which `no_lint_skip` forbids.
    del runner

    # Verify that vendored declarations exist and are non-empty
    committed = _generated_files(repo_root, (inputs or GateInputs()).type_filenames)
    missing = _missing_or_empty(committed)
    if missing:
        rendered = ", ".join(str(path) for path in missing)
        return GateResult(rc=1, stdout=f"missing vendored declarations: {rendered}\n")

    findings = claude_types.check(repo_root)
    if findings:
        return GateResult(rc=1, stdout="\n".join(findings) + "\n")

    # Type-checking is handled by typecheck_modules() below
    return GateResult(rc=0)


def _emit(result: GateResult) -> None:
    """Preserve the external tools' measured stdout/stderr split."""
    sys.stdout.write(result.stdout)
    sys.stderr.write(result.stderr)


def fnhook_gates_main(
    argv: Sequence[str] | None = None,
    *,
    runner: Runner = default_runner,
    repo_root: Path | None = None,
    inputs: GateInputs | None = None,
) -> int:
    """Run all function-hook build gates for the current repository."""
    if argv:
        sys.stderr.write("fnhook-gates takes no arguments\n")
        return 2
    repo_root = (repo_root or Path.cwd()).resolve()
    inputs = inputs or GateInputs()
    plugin_dirs = discover_plugin_dirs(repo_root, fixture_root=inputs.fixture_root)
    results = [validate_plugin(path, runner=runner) for path in plugin_dirs]
    results.extend(
        (
            assert_modules_are_typed(plugin_dirs),
            assert_escape_hatch_permitted(plugin_dirs),
            typecheck_modules(plugin_dirs, runner=runner, repo_root=repo_root, inputs=inputs),
            _check_types_current(repo_root, runner=runner, inputs=inputs),
        )
    )
    rc = 0
    for result in results:
        _emit(result)
        if not result.ok:
            rc = 1
    return rc
