# Copyright (c) 2026 Raymond Manaloto
"""Review-owned #301 authority roots, intentionally outside planner identity."""

PROTOTYPE_CONTRACT_SHA256 = "b7a41ea639efc28a714e1f1faa47dcdc69c6d5b8cdf17719c7a78fffaa583848"
PROTOTYPE_LAUNCHER_SHA256 = "f8810dc9d069260c4d4976c312f117386b1d1a134720180e88ec4577cd9fb428"

# RE-AUTHORIZED by Ray, 2026-08-16, against the plan regenerated at graphify
# 0.9.45 (source commit 0738af37): 792 files / ~1,394,475 words -> 474 units / 58
# chunks, extracted by `claude-opus-5` at `--effort high`.
#
# WHAT MOVED, and what did not — the paragraph below used to say the two
# decision-bearing digests "have never changed", and at 0.9.45 both did. They were
# diffed rather than re-recorded on that assurance, and the assurance survives in
# substance: `exclusions.json` differs ONLY in `source_commit`/`source_tree` (the
# same four entries, unchanged), and `advisories.json` differs only in those two
# fields plus the observed census. Same advisory code, same thresholds, same
# decision. So the digests moved for IDENTITY and CENSUS reasons, and no reviewed
# judgement changed.
#
# The extraction workload is also unchanged, which is the fact that made this a
# re-record rather than a fresh review: the admitted inventory is the same 370
# unique paths — zero added, zero removed, checked as sets — yielding the same
# 474 units and 58 chunks. The +1 file lives in the advisory's whole-tree census,
# not in anything that will be sent to a provider.
#
# RE-RECORDED again at 31c63d4d, and the reason is this mechanism demonstrating
# itself: that commit changed nothing but a COMMENT in
# `graphify_semantic_corpus_run.py`, and a comment moves the file's bytes, so
# `runner_sha256` moved, so `execution-config.json` moved, so this authorization
# was stale and `kb-ship` refused. Documented one commit earlier and walked into
# anyway — recorded here because the surprise is the useful part: "no executable
# line changed" is NOT the same predicate as "the digest did not move".
#
# The re-plan is the cleanest available evidence that only the CODE identity
# moved: `advisories_sha256` (ce1da16e) and `exclusions_sha256` (9aeb4c1b) came
# back BYTE-IDENTICAL, and only `execution_config_sha256` and the manifest
# containing it changed. The reviewed decisions are untouched, so this re-records
# the same judgement rather than asking for a new one.
#
# Prior authorization: 2026-08-16 at 0.9.44 (source commit 4fca6215), 791 files /
# ~1,391,691 words, same 474 units / 58 chunks.
#
# What was reviewed, because four digests record THAT a review happened and not
# WHAT it concluded:
#
# * The cost advisory — graphify's own "large corpus, consider a subfolder"
#   warning. Acknowledged: whole-tree is the deliberate scope, not an oversight.
# * Four exclusions, each derived or presentational and each leaving its semantic
#   authority in the corpus: `docs/demo-path.svg` (regenerated by
#   `scripts/gen_demo_path.py`), `docs/graph-hero.png` and `docs/logo.png`
#   (presentation assets described by `README.md`), and
#   `worked/rsl-siege-manager/graph.html` (a rendering of the adjacent
#   `graph.json`). No document carrying meaning of its own is dropped.
#
# These digests are of the plan's exact bytes, so ANY re-plan invalidates them
# and `verify` reports `plan-authority-mismatch` rather than authorizing a plan
# nobody read. That is the intended behaviour: re-authorize deliberately.
# Re-recorded after `runner_sha256` was added to the execution config (cold-lane
# finding: the authorization pinned the planner, adapter and slice but not the
# module that actually makes the calls). The two digests that carry the REVIEWED
# DECISIONS are byte-identical across every re-plan since — `advisories_sha256`
# and `exclusions_sha256` below have never changed — so this re-records the same
# judgement over a config that now pins strictly more. Only
# `execution_config_sha256` and the manifest that contains it moved.
#
# The consequence is deliberate and worth knowing before it surprises someone:
# editing the driver, the slice, the adapter or the planner now invalidates this
# authorization, because their digests are inside the config it is a digest of.
# `test_recorded_authority_authorizes_this_plan_and_only_this_plan` fails the
# moment that happens, which is the intended behaviour rather than friction — an
# authorization is a review of what a run WILL DO, and the code that will do it
# changed. Re-plan and re-record, and say what moved.
# RE-RECORDED 2026-08-17, after the round that closed a cold cross-family lane's
# four HIGH findings in the driver, the slice and the adapter. Same judgement,
# same workload — this is the code-identity case this file's doctrine above
# describes, and it was verified rather than asserted.
#
# WHAT MOVED: exactly six fields of `execution-config.json`, and the manifest
# containing it. Four are the digests of the files this round edited —
# `runner_sha256`, `semantic_slice_sha256`, `adapter_sha256`, `planner_sha256` —
# and `cache_namespace_sha256` is derived from them.
#
# The sixth is the one that is NOT mere identity, and it is a CORRECTION rather
# than a change of intent: `cache_policy` was `warm-read-atomic-per-chunk` and is
# now `checkpoint-write-atomic-per-chunk`. The old value asserted a cache READ
# this call path never performs — measured, not assumed — so the field described
# behaviour the run could not exhibit. Nothing about what the run DOES changed;
# what changed is that the record stopped being false. Same model, same
# `--effort high`, same budget, same concurrency of 1, same retry depth, same
# chunk size.
#
# WHAT DID NOT: `advisories.json`, `exclusions.json`, `source-inventory.json` and
# `chunk-ledger.json` all came back BYTE-IDENTICAL, at the same source commit
# 0738af37 — so both digests carrying a reviewed DECISION are unchanged, and the
# workload is the same 474 units / 58 chunks over the same 370 admitted paths.
# Nothing here asks for a judgement Ray has not already given; a moved advisory
# or exclusion digest would, and would be escalated rather than re-recorded.
#
# RE-PLANNED TWICE this round, and the second time is the lesson. The first
# re-plan verified `execution_authorized: true`, and a later edit to the slice
# and the adapter — made to close the same round's findings — moved their digests
# again and silently invalidated it. `verify` had already said yes, so the stale
# authorization surfaced only when the suite ran. RE-PLAN LAST: any edit to the
# driver, slice, adapter or planner after the re-plan un-authorizes it, and a
# green `verify` is evidence about the tree at the moment it ran and nothing
# after.
#
# RE-RECORDED 2026-08-17 (b), after a pure-readability refactor of the adapter
# that carries no behavioural change: `adapter_main` lost its inline reason
# collection and its inline rejection reporting to two module-level helpers,
# `_completion_reasons` and `_report_rejection`. It was done because the third
# party health check on PR #331 attributed the ENTIRE health regression of this
# round to one function — `adapter_main` at cyclomatic 9 with three nested
# blocks at the same level — and the remedy for a complexity finding is to
# reduce the complexity, not to reclassify the check. Measured both ways with a
# second, independent probe: `ruff check --select C901` read the same 9 before
# and reads 6 after, below the 8 this function carried at `df4001df`, the last
# commit at which the check passed.
#
# THAT PROBE'S CONDITION, because the number is meaningless without it: it was
# run at `--config "lint.mccabe.max-complexity=5"`, NOT at this repo's
# configured limit of 10. This function has never failed our own ruff gate, at
# either complexity, and this refactor did not make a red gate green. The
# lowered threshold exists only to make ruff report the same METRIC the external
# check reports, so the two could be compared — and they agreed exactly at 9,
# which is what made the external finding actionable instead of a black box.
#
# WHAT MOVED: exactly two fields of `execution-config.json`, and the manifest
# containing it. `adapter_sha256` is the digest of the file that was edited, and
# `cache_namespace_sha256` is derived from it. Nothing else in the config
# differs — diffed field by field against the previous plan rather than assumed.
#
# WHAT DID NOT: `advisories.json`, `exclusions.json`, `source-inventory.json`
# and `chunk-ledger.json` came back BYTE-IDENTICAL at the same source commit
# 0738af37, so both digests carrying a reviewed DECISION are unchanged and the
# workload is the same 474 units / 58 chunks. This asks for no judgement Ray has
# not already given.
# RE-RECORDED 2026-08-17 (c), after Ray's two spend rulings of the same day. This
# is the first re-record in this file that changes what the run is AUTHORIZED TO
# SPEND, rather than only which bytes will do the spending — so it is a new
# judgement being recorded, not the same one re-signed, and it says so plainly.
#
# WHAT MOVED, and why each one moved:
#
# * `max_total_cost_usd` — a NEW field, absent -> 100.0. Ray's ruling. Nothing in
#   the plan bounded the WHOLE run: `max_cost_usd` is per chunk and
#   `--max-budget-usd` is per provider invocation, so 58 chunks each individually
#   within authority could spend an unbounded total (chunk 1 measured 1.12 USD,
#   the corpus projects to about 65, the per-chunk ceiling permits about 1,450).
#   The field has NO DEFAULT, so a plan written before it existed is refused
#   rather than run uncapped.
# * `claude_max_output_tokens` — 8192 -> 64000. Ray's ruling: resolve the model's
#   real ceiling at PLAN TIME and pin half of it. 8192 was a literal chosen when
#   nothing here could resolve a ceiling; Opus 5's real ceiling is 128,000, and
#   half leaves roughly 2x the measured ~31,887-token need while still being a
#   bound. `model_limits` RAISES rather than falling back to a literal, so a
#   resolution failure cannot silently reinstate the number this removes.
# * `adapter_sha256`, `planner_sha256`, `runner_sha256`, `semantic_slice_sha256`
#   — the four modules this round edited, and `cache_namespace_sha256` is derived
#   from them. Ordinary code identity, the case this file's doctrine describes.
# * `claude_version` 2.1.233 -> 2.1.234, and `claude_executable_sha256` with it.
#   Claude Code self-updated under the session. The `--help` digest did NOT move
#   (71ad650f…, the same value 2.1.232 and 2.1.233 both recorded), re-hashed
#   against the INSTALLED binary through the slice's own child environment — so
#   every required flag, the argv shape and the envelope this path pins are
#   unchanged and only the implementation moved. Without this advance the run
#   would have refused at preflight, correctly, on a version nobody had reviewed.
#
# RE-PLANNED FIVE TIMES this round, each one caused by an edit to a digested
# module after the previous plan. RE-PLAN LAST is the rule; what this round adds
# is that a CURRENCY REVIEW and a REVIEW ROUND are both code changes here, so
# each belongs before the re-plan however unrelated it feels.
#
# The fifth was the cold review itself: closing its P1 moved the completeness
# decision into `completeness_rc`, and its `model_limits` findings edited that
# module too. Both are inside this config. So the ordering that actually works is
# review -> fix -> re-plan -> re-record, and any attempt to re-plan earlier is
# work that will be redone.
#
# The fourth re-plan is worth its own sentence, because it was a real defect
# rather than sequencing. Advancing "the accepted Claude version" to match the
# self-updated binary turned the COMMITTED SLICE CANDIDATE from `unapproved` to
# `failed`: `_ACCEPTED_CLAUDE_*` is the authority for evidence that already
# exists, and no edit can change what already ran. The corpus planner needs the
# opposite thing — what a run WILL use — so the slice now carries an
# `_ACCEPTED_`/`_CURRENT_` pair for Claude exactly as it already did for graphify,
# and this plan reads `current_claude()`. The suite caught it; reading the diff
# had not.
#
# ONE MORE FIELD MOVED AND IT IS NOT THIS ROUND'S DOING, which is worth recording
# because it looks like an unexplained change: `timeout_seconds` 900 -> 120. The
# plan that was on disk had been generated on ANOTHER BRANCH
# (`fix-328-extraction-warning-accounting`, where the timeout work lives) and
# never matched this branch's planner, whose value has been 120 throughout. The
# re-plan did not lower a timeout; it stopped a foreign plan from standing in for
# this branch's. That stale plan is also why the authority-digest test was red
# before any of this round's edits.
#
# WHAT DID NOT MOVE: `advisories.json` and `exclusions.json` came back
# BYTE-IDENTICAL (ce1da16e and 9aeb4c1b, the same values recorded above), as did
# `source-inventory.json` and `chunk-ledger.json`, at the same source commit
# 0738af37. Both digests carrying a reviewed DECISION are unchanged and the
# workload is the same 474 units / 58 chunks over the same 370 admitted paths, so
# nothing here re-opens the scope question — only the spend bounds are new, and
# both were ruled explicitly.
# RE-RECORDED 2026-08-17 (c), after the one-line fix that made this corpus
# extractable AT ALL. Same judgement, same workload, and the narrowest re-plan this
# file has yet recorded.
#
# WHY: the driver passed its temporary evidence directory to the adapter as
# `tempfile` spells it, unresolved. `write_provider_boundary_start` opens every
# component of that directory with `O_NOFOLLOW`, and `$TMPDIR` on macOS is
# `/var/folders/…` where `/var` is a symlink to `private/var` — so the marker was
# refused before any provider call. Measured, not inferred: the first run against
# this plan failed **58 of 58** chunks with `provider boundary marker destination is
# unavailable`, and it cost nothing, because the marker is written BEFORE the
# invocation. The semantic SLICE never hit it: its evidence lives in
# `graphify-out/graphify-semantic-slice/`, an in-repo path with no symlink
# component, and until now the slice was the only path that had ever run.
#
# The fix is `trusted_evidence_dir`, in the CALLER. It is deliberately not in
# `open_directory_nofollow`, which must keep refusing symlinks for callers whose
# path components are not trusted; a test asserts that guard survived rather than
# being quietly relocated into the primitive.
#
# WHAT MOVED: exactly TWO of the 43 fields of `execution-config.json`, diffed field
# by field rather than assumed — `runner_sha256` (the edited file) and
# `cache_namespace_sha256` (derived from it) — plus the manifest containing it.
#
# WHAT DID NOT: `advisories.json`, `exclusions.json`, `source-inventory.json` and
# `chunk-ledger.json` all came back BYTE-IDENTICAL at the same source commit
# 0738af37, so both digests carrying a reviewed DECISION are unchanged. Workload
# re-derived from the new plan rather than carried forward: **474 units / 58 chunks
# over 370 unique admitted paths**. This asks for no judgement Ray has not given.
#
# RE-PLANNED TWICE AGAIN, and the doctrine above earned its place a second time.
# The first re-plan of this round verified `execution_authorized: true`, and then the
# guard work landed — `assert_canonical_evidence`, the `__post_init__` that calls it,
# and a comment corrected after a mutation refuted it — all in the same driver file,
# so `runner_sha256` moved again and `verify` went to `config-contract-mismatch`.
# RE-PLAN LAST is not advice about tidiness: a green `verify` is evidence about the
# tree at the instant it ran and nothing after it. The second re-plan moved exactly
# the same two fields (`runner_sha256`, `cache_namespace_sha256`) of 43 and left all
# four decision-bearing files byte-identical.
# AUTHORIZED ANEW 2026-08-17 (d), and this one is NOT a re-record. Every prior entry
# in this file moved only code-identity digests and could honestly say "same judgement";
# this changes WHAT THE RUN DOES, so it rests on a decision Ray gave explicitly.
#
# THE DECISION: `timeout_seconds` 120 -> 900. Ray chose 900 s from three measured
# options on 2026-08-17, and chose to KEEP `concurrency = 1`.
#
# THE MEASUREMENT it rests on, because a timeout picked by feel is how the old one got
# there. Chunk 1 — 7 members, 18,218 estimated tokens, a MEDIAN chunk of the 58 (range
# 13,067 to 19,989) — completed in **659.5 s at rc=0**, returning 434 KB, against a
# 900 s probe ceiling. So 120 s was off by ~5.5x. That figure is a LOWER BOUND: it was
# taken on graphify's own argv, which omits the `--effort high` and `--max-turns 3` the
# adapter adds, and 900 s is 1.36x it precisely to cover that gap.
#
# WHY 120 SURVIVED THIS LONG: an unresolved `$TMPDIR` one layer down had failed all 58
# chunks before any model was called, so the timeout had never once been exercised.
# The two defects were discovered in the same hour, in that order.
#
# WHAT ELSE CHANGED, and it is part of the same fix: the adapter's inference ceiling was
# a hardcoded `timeout=120` reachable from no configuration (#335), so raising this
# field alone would have changed only WHICH 120-second limit killed the call. It now
# reads `GRAPHIFY_API_TIMEOUT` — the variable the driver already sets from this field —
# so the two cannot drift. One number, two consumers.
#
# THE COST, stated so nobody is surprised by it: at ~11 minutes a chunk and
# `concurrency = 1`, 58 chunks is **~10.6 h**. Chunking differently does not change
# that total; only concurrency would, and concurrency stays 1.
#
# WHAT MOVED: 4 of 43 config fields, diffed field by field — `timeout_seconds` (the
# decision), `planner_sha256` and `adapter_sha256` (the two edited files), and
# `cache_namespace_sha256` (derived). WHAT DID NOT: `advisories.json`,
# `exclusions.json`, `source-inventory.json` and `chunk-ledger.json` are BYTE-IDENTICAL
# at source commit 0738af37, so both digests carrying a reviewed exclusion/advisory
# decision are untouched and the workload is the same 474 units / 58 chunks.
#
# RE-RECORDED 2026-08-17 (e), after this branch was rebased onto `main` at
# `e8f7f4ea`. **No new judgement.** Both of the entries above were written on
# branches that could not see each other — the spend rulings landed on `main` via
# PR #336 while the timeout and `$TMPDIR` work sat here — so each recorded a plan
# that was true of its own tree and of no tree that would ever run. The rebase is
# the first time all three of Ray's rulings hold at once, and re-planning is what
# makes the authority describe that tree rather than either parent.
#
# WHAT MOVED, diffed field by field against the pre-rebase plan rather than
# assumed — FIVE of 43:
#
# * `timeout_seconds` 120 -> 900. NOT a new decision: it is the (d) ruling above,
#   arriving in a plan generated from a tree that also carries the spend caps. The
#   120 it replaces is the number the (c) block explains as a foreign plan's value
#   standing in for this branch's, now resolved in the other direction.
# * `planner_sha256`, `runner_sha256`, `adapter_sha256` — the three files the
#   merge touched, and `cache_namespace_sha256` derived from them. Ordinary code
#   identity, the case this file's doctrine describes.
#
# THE TWO FIELDS THE MERGE HAD TO CHOOSE BETWEEN, both verified in the regenerated
# config rather than reasoned about: `claude_max_output_tokens` is **64000**, the
# value #336 RESOLVES at plan time, not the `_PROFILE` literal this branch read;
# and `max_total_cost_usd` is **100.0**, present at all only because the rebase
# brought it. A merge that silently kept this branch's side of either would have
# produced a plan that looks authorized and spends without a cumulative bound.
#
# WHAT DID NOT MOVE: `advisories.json`, `exclusions.json`, `source-inventory.json`
# and `chunk-ledger.json` are BYTE-IDENTICAL at the same source commit 0738af37,
# so both digests carrying a reviewed DECISION are unchanged and the workload is
# the same 474 units / 58 chunks. Nothing here re-opens the scope question.
# RE-RECORDED 2026-08-17 (f), after the cold review of PR #338. **No new
# judgement**, and the narrowest re-plan in this file: exactly TWO of 43 fields,
# `adapter_sha256` and the `cache_namespace_sha256` derived from it. Every
# decision field — both spend caps, the output ceiling, the timeout, concurrency
# — is unchanged, and all four decision-bearing plan files are BYTE-IDENTICAL at
# source commit 0738af37, so the workload is still 474 units / 58 chunks.
#
# WHY THE ADAPTER MOVED: `inference_timeout_seconds` rejected `0` and negatives
# but passed `inf` and `nan` straight through, because both PASS an ordering test
# — so a non-finite `GRAPHIFY_API_TIMEOUT` reached `subprocess.run` and disabled
# the deadline entirely. That is the unbounded wait the fallback exists to
# prevent, arriving through the guard meant to prevent it, on the one path where
# an unbounded wait costs money. `math.isfinite` now gates it.
#
# This is the third re-plan of this branch and the doctrine holds a third time:
# a REVIEW ROUND is a code change here, so it belongs before the re-plan however
# much it feels like a separate activity.
# RE-RECORDED 2026-08-18 (g), after the first real chunk ran. NO new judgement:
# one field of 43 moved, `runner_sha256`, plus the derived namespace.
#
# WHAT THE RUN FOUND, and neither was reachable by reading:
#
# 1. THE CAP RESET ON EVERY RESTART — fixed here. `_Spend` seeded at 0.0 and
#    summed records living in a `TemporaryDirectory`, so both halves of the
#    accounting died with the process: a run interrupted at chunk 30 resumed with
#    a fresh 100 USD, and `ChunkStageReceipt` carries no cost field to contradict
#    it. A durable `spend-ledger.json` now lives under the run namespace, is
#    written through on every charge, and refuses a plan already over its cap
#    BEFORE the first provider call. It works: the re-prove recorded
#    `{"total_usd":1.3249605,"charges":1}` — the first time this corpus has been
#    able to say what a chunk cost. At 1.32 USD/chunk, 58 chunks projects to
#    ~77 USD against the 100 USD cap, which is tighter than the ~65 estimated.
#
#    Read next to the driver's own note that `extract_corpus_parallel` never
#    consults the incremental cache: a resumed run re-buys every chunk, so a
#    durable cap fires SOONER on a restart. That is the honest cost, previously
#    invisible in both directions.
#
# 2. SCOPE DRIFT — NOT FIXED, and deliberately not papered over. Chunk 1's first
#    run attributed 61 of 109 nodes to 26 files the chunk never contained;
#    `fragment-source-scope-mismatch` refused it, correctly. The attempted fix
#    added a scope clause to `_EXTRACTION_USER_INSTRUCTION` — and that constant is
#    a MIRROR of text `graphify.llm` hardcodes. graphify builds the prompt itself
#    and pipes it to our adapter over stdin; `graphify.llm` never references
#    `kb_setup`. So the change could not reach the prompt, altered only our
#    RECONSTRUCTION of it, and produced `provider-prompt-bytes-mismatch`: the fix
#    WAS the defect. Reverted byte-exactly, which is why `prompt_contract_sha256`
#    and `planner_sha256` are back to the values the (f) block recorded.
#
#    The second run is why this is still open rather than closed: same 5 members,
#    same source commit, same graphify-built prompt — and 0 out-of-scope nodes
#    instead of 61. The drift is NONDETERMINISTIC, so one clean run is not
#    evidence of a fix, and one dirty run is not evidence of a permanent defect.
#    What is established is that the staging gate catches it either way. Closing
#    it needs a graphify-side prompt hook or a post-hoc decision, and that is a
#    judgement for Ray, not something to infer from two samples.
#
# RE-RECORDED once more the same day, after a cold review of the ledger itself
# found `charges` resetting on resume while `total_usd` carried — so the record
# reported `{total_usd: 6.0, charges: 1}` after three charges, contradicting its
# own total in the one file a finished run can be audited from. `runner_sha256`
# and the derived namespace moved; nothing else did.
#
# WHAT DID NOT MOVE: `advisories.json`, `exclusions.json`, `source-inventory.json`
# and `chunk-ledger.json` are BYTE-IDENTICAL at source commit 0738af37, so both
# digests carrying a reviewed DECISION are unchanged and the workload is the same
# 474 units / 58 chunks. No spend bound was loosened — one was made to survive the
# thing that was defeating it.
# RE-RECORDED 2026-08-19 against the plan regenerated at graphify 0.9.46 (source
# commit 558df6d5). Ray's ruling for this advance was explicit: MEASURE the
# admitted inventory first, and re-record only if it is unchanged — otherwise the
# cost moved and it is a fresh review, not a re-record.
#
# It is unchanged, and that is the whole justification. Measured by building the
# real plan through `plan_source` with the real `planned_max_output_tokens`
# resolver, exactly as `_exact_graphify_plan` does:
#
#     unique admitted paths  370   (0.9.45: 370)
#     units                  474   (0.9.45: 474)
#     chunks                  58   (0.9.45:  58)
#
# So nothing additional will be sent to a provider and the projected spend is
# unmoved. The specific risk this measurement was aimed at: 0.9.46 adds
# `graphify/extractors/commonlisp.py` — production source, which could plausibly
# have entered the admitted set and changed the cost. It did NOT; zero
# lisp-related paths are admitted, and neither is the extractor itself. The other
# five files 0.9.46 adds are a `.lisp` fixture and four test modules.
#
# What DID move, and why each is identity or census rather than judgement:
#
#   * `exclusions.json` — still the SAME FOUR entries; only `source_commit` and
#     `source_tree` differ. No reviewed judgement changed.
#   * `advisories.json` — same code, same thresholds, same `provisional` status;
#     the census moved 792 files / ~1,394,475 words -> 798 / ~1,406,076, which is
#     the six added files in the whole-tree count, none of them admitted.
#   * `execution-config.json` and `manifest.json` — pin identity.
#
# This is the same shape as the 0.9.45 re-record, and it is recorded here rather
# than merely believed because the previous note had to be corrected once: the
# digests were once described as never changing, and then they changed.
#
# RECORD THIS BLOCK LAST — after every other edit in the change is final.
# `execution-config.json` hashes `planner_sha256` (this package's corpus module)
# and `semantic_slice_sha256` among others, so ANY later edit to those files,
# including a one-word comment fix, moves two of the four digests below and
# stales the authorization. That is not hypothetical twice over: the note above
# records it happening at 31c63d4d for a comment in the runner, and it happened
# AGAIN while writing this very entry — the four values were computed, then a
# typo fix landed in `graphify_semantic_corpus.py` and a public-alias change in
# `graphify_semantic_slice.py`, and `execution_config_sha256` /
# `plan_manifest_sha256` both drifted before the commit was made. The gate caught
# it, which is the gate working; the ordering rule is how not to need it.
# RE-RECORDED 2026-08-19 (h), for the graphify v0.9.46 -> v0.9.47 currency bump.
# **NO NEW JUDGEMENT.** Every decision field is unchanged and that was VERIFIED
# field by field against the previous plan rather than asserted:
#
#     max_total_cost_usd        100.0  ->  100.0
#     max_cost_usd               25.0  ->   25.0
#     claude_max_output_tokens  64000  ->  64000
#     timeout_seconds             900  ->    900
#     concurrency                   1  ->      1
#     max_turns                     3  ->      3
#
# FOURTEEN of 44 fields moved, and every one is IDENTITY:
#
# * `graphify_ref` / `graphify_commit` / `graphify_tree` / `graphify_version` /
#   `graphify_runtime` — the pin, and its wheel and sdist digests, which move
#   because the distribution is a new build. `sdk_fingerprint_sha256` is
#   UNCHANGED (b10406f9…), the same value 0.9.45 and 0.9.46 both recorded, so
#   the public SDK surface is identical at all three.
# * `graphify_llm_sha256` — 0.9.47 fixes an `AttributeError: 'ThinkingBlock'`
#   crash when an extended-thinking response leads with a thinking block
#   (#2697). That is the CLAUDE backend, i.e. the only backend this repo
#   permits, so it is a reason to adopt rather than a risk.
# * `claude_version` / `claude_executable_sha256` 2.1.235 -> 2.1.236 — `claude`
#   self-updated in place. The `--help` digest did NOT move, so every flag this
#   path depends on is spelled identically.
# * `planner_sha256`, `semantic_slice_sha256`, and the four digests derived from
#   the plan's own members — ordinary code identity, the case this file's
#   doctrine describes.
#
# BOTH DECISION-BEARING FILES MOVED THIS TIME, which is a first for this file and
# is why each was diffed rather than re-digested:
#
# * `exclusions.json` — ONLY `source_commit` and `source_tree` changed. Every
#   exclusion ENTRY is byte-identical, so no scope question is re-opened.
# * `advisories.json` — `detector_git_object` (the detect.py blob, whose diff is
#   read at `_ACCEPTED_GRAPHIFY_DETECT_OBJECT` in `graphify_semantic_corpus.py`
#   and touches no detection logic) plus the OBSERVED census: 798 -> 803 files
#   and 1,406,076 -> 1,415,411 words. Both thresholds — 500 files, 500,000 words
#   — are unchanged. An observation moving is not a decision moving.
#
# WORKLOAD: 474 -> 475 admitted units, still 58 chunks, `detected_source_count`
# unchanged at 374. Worth stating because it is not predictable from the release
# diff: upstream added FIVE files, all `tests/*.py`, and the admitted unit count
# moved by ONE.
#
# ORDERING, the rule this file has had to restate seven times: this block was
# written AFTER the cold review's two rounds and after every fix from both, so
# `planner_sha256` and `semantic_slice_sha256` were final when the four digests
# below were computed. That is the point of recording it last — round 2 changed
# `graphify_semantic_corpus.py` and `graphify_semantic_slice.py`, and recording
# before it would have staled these values exactly as the note above describes
# happening at 31c63d4d.
# RE-RECORDED 2026-08-20 (i), for the graphify v0.9.47 -> v0.9.48 currency bump
# and the claude 2.1.236 -> 2.1.238 self-update. **NO NEW JUDGEMENT.** Every
# decision field is unchanged and that was VERIFIED field by field against the
# previous plan rather than asserted:
#
#     max_total_cost_usd        100.0  ->  100.0
#     max_cost_usd               25.0  ->   25.0
#     claude_max_output_tokens  64000  ->  64000
#     timeout_seconds             900  ->    900
#     concurrency                   1  ->      1
#     max_turns                     3  ->      3
#     graphify_max_retry_depth      2  ->      2
#
# Ray's standing ruling for a graphify advance is MEASURE THE ADMITTED INVENTORY
# FIRST and re-record only if it is unchanged — otherwise the cost moved and it
# is a fresh review. It is unchanged, and that is the whole justification.
# Measured through `plan_source` with the real `planned_max_output_tokens`
# resolver, exactly as `_exact_graphify_plan` does, and diffed against the plan
# on disk (whose four digests match the values this block replaces, so it IS the
# authorized plan and not a look-alike):
#
#     detected sources       374   (0.9.47: 374)
#     discovered units       479   (0.9.47: 479)
#     admitted units         475   (0.9.47: 475)
#     chunks                  58   (0.9.47:  58)
#     unique admitted paths  370   (0.9.47: 370) — zero added, zero removed,
#                                   compared as SETS so an over-covering plan
#                                   would fail too rather than pass by count
#
# Estimated tokens moved 1,037,295 -> 1,038,052 (+757, +0.07%), all of it
# CHANGELOG.md and README.md growing at the release. Six of 58 chunks differ and
# every one of those differences is that growth plus a one-slot `unit_ordinal`
# shift behind it — no unit entered or left. The projected spend is unmoved.
#
# THIRTEEN of 44 config fields moved, and every one is IDENTITY or derived:
#
# * `graphify_ref` / `graphify_commit` / `graphify_tree` / `graphify_llm_sha256`
#   — the pin.
# * `claude_version` / `claude_executable_sha256` 2.1.236 -> 2.1.238. `claude`
#   self-updated in place twice; 2.1.237 was never resident here long enough to
#   be recorded. The `--help` digest did NOT move — still 71ad650f…, the value
#   2.1.232 through 2.1.236 all recorded, re-hashed against the INSTALLED
#   binary through the slice's own `claude_child_environment` — so every flag
#   this path pins is spelled identically and only the implementation moved.
# * `planner_sha256` / `semantic_slice_sha256` and the four digests derived from
#   the plan's own members — ordinary code identity.
#
# TWO THINGS MOVED THAT THIS FILE HAS NEVER RECORDED MOVING, and neither is a
# decision. Both were checked rather than reasoned about, because each one is
# exactly the shape that would carry a real change in disguise:
#
# 1. `exclusions.json` ENTRY BYTES moved — a first. `docs/graph-hero.png` and
#    `docs/logo.png` carry `evidence_git_objects` / `evidence_sha256` binding
#    them to the README that DESCRIBES them, and that README changed at 0.9.48.
#    The two entries whose evidence did not change — `docs/demo-path.svg` and
#    `worked/rsl-siege-manager/graph.html` — are byte-identical. So the evidence
#    DOCUMENT moved under an unchanged judgement: still the same four
#    exclusions, still each one derived or presentational with its semantic
#    authority left in the corpus. No scope question is re-opened.
#
# 2. `graphify_semantic_fingerprint_sha256` moved (43122fca… -> 6047cf0e…) —
#    a REAL signature change in the one API this run calls.
#    `extract_corpus_parallel`'s `max_retry_depth: int = 3` became
#    `int | None = None`, resolved by a new `_resolve_max_retry_depth()` that
#    honours `GRAPHIFY_MAX_RETRY_DEPTH` (upstream #2880, so an operator can cap
#    retry spend from the CLI). It has NO EFFECT HERE, and that was established
#    by reading the call sites rather than the release note: the driver passes
#    `max_retry_depth=config.graphify_max_retry_depth` EXPLICITLY at all three
#    of them, and the new default resolution — and therefore the environment
#    variable — is reachable only when the argument is `None`. Worth recording
#    rather than waving through, because a fingerprint that moves is the one
#    signal this plan has that the surface it depends on changed, and the
#    correct response to it is to go and read what changed.
#
# `advisories.json` moved only in the OBSERVED CENSUS: 803 -> 807 files and
# 1,415,411 -> 1,425,243 words. Same advisory code, same 500-file and
# 500,000-word thresholds, same `detector_git_object` (d16b5800…), same
# `provisional` status. An observation moving is not a decision moving — and
# `review_status` STAYS `provisional` deliberately: `verify_plan` requires that
# exact value, and `cost-advisory-review-required` is emitted only inside the
# `if not authorized` branch alongside `plan-authority-mismatch`. Those two
# reasons are companions to the mismatch, never independent gates, so
# "clear the advisory" is not a thing that can be done to this plan — recording
# it because a handoff read them as three separate blockers and they are one.
#
# ORDERING, the rule this file has now had to restate eight times: this block
# was written AFTER the claude constant advanced in `graphify_semantic_slice.py`
# and after the census assertion in `tests/test_graphify_semantic_corpus.py` was
# updated, so `semantic_slice_sha256` was final when the four digests below were
# computed. The test file is not digested; the slice is.
# RE-RECORDED 2026-08-20 (j), after PR #422's bot round found a LIVE BREAK in
# `graphify_semantic_slice`. **NO NEW JUDGEMENT**, and the narrowest re-plan in
# this file: exactly TWO of 44 fields, `semantic_slice_sha256` and the
# `cache_namespace_sha256` derived from it. `advisories.json` and
# `exclusions.json` are BYTE-IDENTICAL to the (i) values above — both digests
# carrying a reviewed DECISION are untouched — as are `source-inventory.json`
# and `chunk-ledger.json`, so the workload is the same 475 units / 58 chunks.
# Every decision field is unchanged: 100.0 / 25.0 / 64000 / 900 / 1 / 3 / 2.
#
# WHY THE SLICE MOVED, because it is worth more than its digest:
# `_runtime_reasons` matched `(graphify_runtime, graphify_version)` against
# accepted pairs whose version half was HAND-WRITTEN beside the runtime half.
# The 0.9.46 -> 0.9.47 bump advanced `_CURRENT_GRAPHIFY_RUNTIME` and left its
# literal at "0.9.46", so the pair was unmatchable and the non-authority path
# rejected EVERY run under the installed version. The fix DERIVES the version
# half from the runtime half, and advances the constant to the measured 0.9.48.
#
# THREE THINGS ABOUT IT ARE WORTH RECORDING RATHER THAN JUST FIXING:
#
# 1. The comment at that site PREDICTED this failure in these words — "a literal
#    left beside a newer runtime makes the pair unmatchable and the non-authority
#    path rejects every run under the installed version" — having been written
#    after the same slip at 0.9.46. It then happened again one bump later. Prose
#    that forecasts a defect does not prevent it; deriving the value does.
# 2. NOTHING IN THIS REPO CAUGHT IT. The suite was rc=0 throughout, because no
#    test exercised the non-authority path. A cold cross-family lane read the
#    diff and missed it; so did the author. CodeRabbit — which this repo's own
#    doctrine correctly calls advisory rather than a gate — is what found it.
#    An advisory reviewer being the only one to see something is an argument
#    about the gates, not about the reviewer.
# 3. THE FIX'S OWN FIRST TEST WAS INSUFFICIENT, and a mutation sweep is what
#    said so. `kb-arms` R5 reverted the constant to 0.9.47 and SURVIVED: the
#    self-consistency test proves the pair agrees with ITSELF, which stays true
#    when both halves are stale. It caught the RESTATEMENT half of the defect and
#    not the STALENESS half. A second test binds the constant to
#    `sources/graphify.manifest`'s pinned ref, and the sweep then ran 5/5 died,
#    1/1 control held.
#
# WHAT WAS DELIBERATELY NOT FIXED, so its absence is not read as its absence
# being unnoticed: `receipt-semantic-fingerprint-mismatch` compares against
# `_ACCEPTED_SEMANTIC_FINGERPRINT_SHA256` on BOTH paths, and that digest moved
# at 0.9.48 (the `max_retry_depth` signature change, upstream #2880). It is the
# same class — a frozen-evidence constant applied to the non-authority path —
# but it has a different owner and changing it is a judgement about what the
# authority split means, not a typo repair.
#
# RE-RECORDED 2026-08-22 for claude 2.1.238 -> 2.1.240, and for NOTHING ELSE.
# graphify stays at 0.9.48; the only input that moved is `_CURRENT_CLAUDE_*` in
# `graphify_semantic_slice.py`, which the execution config carries.
#
# RAY'S RULING — measure the admitted inventory first, re-record only if it is
# unchanged — is met, and met by a TWO-ARM measurement rather than by re-quoting
# counts from the last re-record. Both arms build the real plan through
# `plan_source` with the real `planned_max_output_tokens` resolver, differing
# ONLY in the claude constants:
#
#   member                  control (2.1.238)   this change (2.1.240)
#   advisories.json         ff7323b1…          ff7323b1…   UNCHANGED
#   exclusions.json         1a63e483…          1a63e483…   UNCHANGED
#   chunk-ledger.json       37aaa462…          37aaa462…   UNCHANGED
#   source-inventory.json   f626c002…          f626c002…   UNCHANGED
#   execution-config.json   83a1fc8d…          710dbbfb…   moved
#   manifest.json           25612cb4…          b4b741b5…   moved
#
# `source-inventory.json` and `chunk-ledger.json` coming back BYTE-IDENTICAL is
# a stronger statement than the counts the ruling asks for, and it subsumes them:
# `detected_source_count`, `discovered_unit_count`, `admitted_unit_count`,
# `unit_count`, `token_budget`, `source_ref`/`source_commit`, the chunk count and
# the SET digest of every unit path were each compared and each identical. An
# inventory cannot be unchanged in every field and changed as a set while its
# whole file digest holds.
#
# THE CONTROL ARM ALSO PROVES THE RECORDED AUTHORITY IS THIS PLAN, not a
# look-alike — the same check the 0.9.48 re-record made. The control's
# `execution-config.json` (83a1fc8d…) and `manifest.json` (25612cb4…) are
# EXACTLY the two values being replaced below, so the plan on disk at 2.1.238 is
# the authorized one and the two moving digests are the only delta.
#
# The two that moved are identity, not judgement: the claude version and
# executable digest live in the execution config, and the manifest contains that
# config's digest. `advisories_sha256` and `exclusions_sha256` have still never
# changed, which is the invariant this block has asserted since it was written.
#
# WHY THIS RE-RECORD EXISTS AT ALL, since the alternative was cheaper: advancing
# `_CURRENT_CLAUDE_VERSION` un-authorizes the plan, and `verify_plan` then emits
# `plan-authority-mismatch` with its two companions — which is ONE blocker, not
# three (they are constructed inside the same `if not authorized` branch). The
# cheap alternative was to leave the constant at 2.1.238 and file the drift, but
# that asserts an identity the host contradicts. Ray ruled re-record, 2026-08-22.
AUTHORITY_JSON = (
    b'{"advisories_sha256":"ff7323b1921752cf195f0869b17f348903ffd8a196248be3c5edcece4fcc93d9",'
    b'"execution_config_sha256":"710dbbfb2d15ac05c9857bd6f0e14ed03a9b7a858e85936a9adbda568938d9da",'
    b'"exclusions_sha256":"1a63e48336f7130a1f68c57340706fd5cea3cbacf12c363bb339a7cae3e5b67e",'
    b'"plan_manifest_sha256":"b4b741b5f0bb992c16f42b57f1e855c751e2de1c331dde1f979c1b80c8fad719",'
    b'"schema_version":1}\n'
)
