# Copyright (c) 2026 Raymond Manaloto
"""Review-owned #301 authority roots, intentionally outside planner identity."""

PROTOTYPE_CONTRACT_SHA256 = "b7a41ea639efc28a714e1f1faa47dcdc69c6d5b8cdf17719c7a78fffaa583848"
PROTOTYPE_LAUNCHER_SHA256 = "f8810dc9d069260c4d4976c312f117386b1d1a134720180e88ec4577cd9fb428"

# RE-AUTHORIZED by Ray, 2026-08-16, against the plan regenerated at graphify
# 0.9.45 (source commit 0738af37): 792 files / ~1,394,475 words -> 474 units / 58
# chunks, extracted by `claude-opus-5` at `--effort high`.
#
# WHAT MOVED, and what did not — the paragraph below used to say the two
# decision-bearing digests "have never changed", and at 0.9.45 both did. They were
# diffed rather than re-recorded on that assurance, and the assurance survives in
# substance: `exclusions.json` differs ONLY in `source_commit`/`source_tree` (the
# same four entries, unchanged), and `advisories.json` differs only in those two
# fields plus the observed census. Same advisory code, same thresholds, same
# decision. So the digests moved for IDENTITY and CENSUS reasons, and no reviewed
# judgement changed.
#
# The extraction workload is also unchanged, which is the fact that made this a
# re-record rather than a fresh review: the admitted inventory is the same 370
# unique paths — zero added, zero removed, checked as sets — yielding the same
# 474 units and 58 chunks. The +1 file lives in the advisory's whole-tree census,
# not in anything that will be sent to a provider.
#
# RE-RECORDED again at 31c63d4d, and the reason is this mechanism demonstrating
# itself: that commit changed nothing but a COMMENT in
# `graphify_semantic_corpus_run.py`, and a comment moves the file's bytes, so
# `runner_sha256` moved, so `execution-config.json` moved, so this authorization
# was stale and `kb-ship` refused. Documented one commit earlier and walked into
# anyway — recorded here because the surprise is the useful part: "no executable
# line changed" is NOT the same predicate as "the digest did not move".
#
# The re-plan is the cleanest available evidence that only the CODE identity
# moved: `advisories_sha256` (ce1da16e) and `exclusions_sha256` (9aeb4c1b) came
# back BYTE-IDENTICAL, and only `execution_config_sha256` and the manifest
# containing it changed. The reviewed decisions are untouched, so this re-records
# the same judgement rather than asking for a new one.
#
# Prior authorization: 2026-08-16 at 0.9.44 (source commit 4fca6215), 791 files /
# ~1,391,691 words, same 474 units / 58 chunks.
#
# What was reviewed, because four digests record THAT a review happened and not
# WHAT it concluded:
#
# * The cost advisory — graphify's own "large corpus, consider a subfolder"
#   warning. Acknowledged: whole-tree is the deliberate scope, not an oversight.
# * Four exclusions, each derived or presentational and each leaving its semantic
#   authority in the corpus: `docs/demo-path.svg` (regenerated by
#   `scripts/gen_demo_path.py`), `docs/graph-hero.png` and `docs/logo.png`
#   (presentation assets described by `README.md`), and
#   `worked/rsl-siege-manager/graph.html` (a rendering of the adjacent
#   `graph.json`). No document carrying meaning of its own is dropped.
#
# These digests are of the plan's exact bytes, so ANY re-plan invalidates them
# and `verify` reports `plan-authority-mismatch` rather than authorizing a plan
# nobody read. That is the intended behaviour: re-authorize deliberately.
# Re-recorded after `runner_sha256` was added to the execution config (cold-lane
# finding: the authorization pinned the planner, adapter and slice but not the
# module that actually makes the calls). The two digests that carry the REVIEWED
# DECISIONS are byte-identical across every re-plan since — `advisories_sha256`
# and `exclusions_sha256` below have never changed — so this re-records the same
# judgement over a config that now pins strictly more. Only
# `execution_config_sha256` and the manifest that contains it moved.
#
# The consequence is deliberate and worth knowing before it surprises someone:
# editing the driver, the slice, the adapter or the planner now invalidates this
# authorization, because their digests are inside the config it is a digest of.
# `test_recorded_authority_authorizes_this_plan_and_only_this_plan` fails the
# moment that happens, which is the intended behaviour rather than friction — an
# authorization is a review of what a run WILL DO, and the code that will do it
# changed. Re-plan and re-record, and say what moved.
# RE-RECORDED 2026-08-17, after the round that closed a cold cross-family lane's
# four HIGH findings in the driver, the slice and the adapter. Same judgement,
# same workload — this is the code-identity case this file's doctrine above
# describes, and it was verified rather than asserted.
#
# WHAT MOVED: exactly six fields of `execution-config.json`, and the manifest
# containing it. Four are the digests of the files this round edited —
# `runner_sha256`, `semantic_slice_sha256`, `adapter_sha256`, `planner_sha256` —
# and `cache_namespace_sha256` is derived from them.
#
# The sixth is the one that is NOT mere identity, and it is a CORRECTION rather
# than a change of intent: `cache_policy` was `warm-read-atomic-per-chunk` and is
# now `checkpoint-write-atomic-per-chunk`. The old value asserted a cache READ
# this call path never performs — measured, not assumed — so the field described
# behaviour the run could not exhibit. Nothing about what the run DOES changed;
# what changed is that the record stopped being false. Same model, same
# `--effort high`, same budget, same concurrency of 1, same retry depth, same
# chunk size.
#
# WHAT DID NOT: `advisories.json`, `exclusions.json`, `source-inventory.json` and
# `chunk-ledger.json` all came back BYTE-IDENTICAL, at the same source commit
# 0738af37 — so both digests carrying a reviewed DECISION are unchanged, and the
# workload is the same 474 units / 58 chunks over the same 370 admitted paths.
# Nothing here asks for a judgement Ray has not already given; a moved advisory
# or exclusion digest would, and would be escalated rather than re-recorded.
#
# RE-PLANNED TWICE this round, and the second time is the lesson. The first
# re-plan verified `execution_authorized: true`, and a later edit to the slice
# and the adapter — made to close the same round's findings — moved their digests
# again and silently invalidated it. `verify` had already said yes, so the stale
# authorization surfaced only when the suite ran. RE-PLAN LAST: any edit to the
# driver, slice, adapter or planner after the re-plan un-authorizes it, and a
# green `verify` is evidence about the tree at the moment it ran and nothing
# after.
#
# RE-RECORDED 2026-08-17 (b), after a pure-readability refactor of the adapter
# that carries no behavioural change: `adapter_main` lost its inline reason
# collection and its inline rejection reporting to two module-level helpers,
# `_completion_reasons` and `_report_rejection`. It was done because the third
# party health check on PR #331 attributed the ENTIRE health regression of this
# round to one function — `adapter_main` at cyclomatic 9 with three nested
# blocks at the same level — and the remedy for a complexity finding is to
# reduce the complexity, not to reclassify the check. Measured both ways with a
# second, independent probe: ruff C901 read the same 9 before and reads 6 after,
# below the 8 this function carried at `df4001df`, the last commit at which the
# check passed.
#
# WHAT MOVED: exactly two fields of `execution-config.json`, and the manifest
# containing it. `adapter_sha256` is the digest of the file that was edited, and
# `cache_namespace_sha256` is derived from it. Nothing else in the config
# differs — diffed field by field against the previous plan rather than assumed.
#
# WHAT DID NOT: `advisories.json`, `exclusions.json`, `source-inventory.json`
# and `chunk-ledger.json` came back BYTE-IDENTICAL at the same source commit
# 0738af37, so both digests carrying a reviewed DECISION are unchanged and the
# workload is the same 474 units / 58 chunks. This asks for no judgement Ray has
# not already given.
AUTHORITY_JSON = (
    b'{"advisories_sha256":"ce1da16ed2d71accb10526e45b897599f32453188d19e0a5a2240c95763e2d36",'
    b'"execution_config_sha256":"848fc020a7cd49a96109738664eb3941cb07dd49b933a532b889226a0250c93b",'
    b'"exclusions_sha256":"9aeb4c1b37c1c72188cb9340a2f3e9e6899e5f8c149d9b0b174c7b76fc9df83c",'
    b'"plan_manifest_sha256":"03642ac4bf08e4572a369f028ff0025787afaac2483038f05e82110a8c7d6eab",'
    b'"schema_version":1}\n'
)
