"""Skill lint: a SKILL.md may not instruct a command a mise task already owns.

Ray's standing directive, restated 2026-08-06 and tracked as #128: *skills call
mise tasks that wrap the python library*. Until now that lived only in prose
(`mise-tasks-only.md`, `zero-bash-logic.md`) — and this repo's own doctrine says
markdown alone is "relying on the LLM" and must never be the only layer.

**The reuse is the point, and it is why this module is ~80 lines rather than a
second implementation.** :func:`kb_setup.hook_guard.decide` already owns the
redirect table, the read-only allowlist, and the remediation wording. It is
public precisely so a gate can reach it (see its docstring). So the PreToolUse
guard and this authoring-time lint are two consumers of ONE decision function:

    runtime   — Claude issues a Bash call        -> hook_guard.run()  -> decide()
    authoring — a SKILL.md instructs a command   -> skill_lint.check() -> decide()

A redirect added to ``_REDIRECT`` is therefore enforced in both places at once.
Two tables would drift, and this repo has a filed lesson for exactly that shape
(the `_safe_lane` writer/reader divergence).

The graph named the pattern before it was built: *"Lint messages inject
remediation into agent context" enables "Enforce invariants, don't
micromanage"* (`openai_com_index_harness-engineering.md`, EXTRACTED). So a
finding prints the canonical task, never just a refusal.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from kb_setup import hook_guard

if TYPE_CHECKING:  # pragma: no cover - typing only
    from collections.abc import Callable, Iterator

# One SKILL.md per skill directory. Nested reference/*.md are prose ABOUT the
# workflow, not the instruction surface an agent follows, so they are out of
# scope until one is shown to instruct a command.
DEFAULT_SKILL_GLOB = ".claude/skills/*/SKILL.md"

# Installer-generated by `graphify install --project` and regenerated wholesale
# by `mise run kb-skill-refresh` — not ours to author, so not ours to gate. Same
# carve-out, same reason, as `md_budget.DEFAULT_EXCLUDED_PREFIXES`.
DEFAULT_EXCLUDED_PREFIXES = (".claude/skills/graphify/",)

# A fenced block whose info string marks it executable. A skill's prose and its
# JSON/markdown samples are not instructions; only shell fences are.
_SHELL_FENCE = re.compile(r"^\s*```+\s*(bash|sh|shell|console|zsh)\b", re.IGNORECASE)
_ANY_FENCE = re.compile(r"^\s*```")

# A placeholder line is documentation of a shape, not an instruction to run it.
# `<...>` and `$VAR`-only lines are templates; a leading `#` is a comment.
_PLACEHOLDER_ONLY = re.compile(r"^\s*(#|$)")


@dataclass(frozen=True)
class Finding:
    """One command in one SKILL.md that a mise task already owns."""

    path: str
    line: int
    command: str
    remedy: str


@dataclass(frozen=True)
class Report:
    """The result of one lint run. ``failed`` is the gate's only question."""

    findings: tuple[Finding, ...]
    scanned: tuple[str, ...]

    @property
    def failed(self) -> bool:
        """True when any SKILL.md instructs a command a mise task owns."""
        return bool(self.findings)


def command_lines(raw: str) -> Iterator[tuple[int, str]]:
    """Yield ``(1-indexed line number, command)`` for each instructed command.

    Only lines inside a shell-marked fence count. A skill that *mentions*
    ``graphify query`` in prose is describing the tool, not telling an agent to
    run it — flagging that would make the gate fire on its own documentation,
    which is how a gate loses its readers.
    """
    in_shell = False
    for i, line in enumerate(raw.splitlines(), start=1):
        if _ANY_FENCE.match(line):
            in_shell = bool(_SHELL_FENCE.match(line)) if not in_shell else False
            continue
        if in_shell and not _PLACEHOLDER_ONLY.match(line):
            yield i, line.strip()


def check(
    root: Path,
    *,
    glob: str = DEFAULT_SKILL_GLOB,
    exclude: tuple[str, ...] = DEFAULT_EXCLUDED_PREFIXES,
    decide: Callable[[str], str | None] = hook_guard.decide,
) -> Report:
    """Lint every SKILL.md under ``root`` for commands a mise task owns.

    ``decide`` is injected rather than imported at the call site so a caller can
    gate a different command family without forking this walker, and so a test
    can drive the FAIL direction without depending on graphify's redirect table
    staying the shape it is today.
    """
    findings: list[Finding] = []
    scanned: list[str] = []
    for path in sorted(root.glob(glob)):
        rel = path.relative_to(root).as_posix()
        if rel.startswith(exclude):
            continue
        scanned.append(rel)
        raw = path.read_text(encoding="utf-8")
        for lineno, command in command_lines(raw):
            remedy = decide(command)
            if remedy:
                findings.append(Finding(rel, lineno, command, remedy))
    return Report(tuple(findings), tuple(scanned))


def skill_lint_main(root: Path) -> int:
    """CLI entry: print the report, return 1 on any finding."""
    report = check(root)
    if not report.scanned:
        # A glob that matches nothing is not a pass — it is a gate that never
        # asked the question (`verify-before-advancing.md`: 0 files is a SKIP).
        print(
            f"skill-lint: NO SKILLS MATCHED {DEFAULT_SKILL_GLOB!r} — "
            "the gate did not run. Check the glob before reading this as clean."
        )
        return 1
    for f in report.findings:
        print(f"skill-lint: {f.path}:{f.line}: {f.command}")
        print(f"            {f.remedy}")
    n = len(report.scanned)
    if report.failed:
        print(
            f"skill-lint: {len(report.findings)} finding(s) across {n} skill(s). "
            "A SKILL.md instructs a command a mise task already owns; skills call "
            "mise tasks that wrap the python library (#128)."
        )
        return 1
    print(
        f"skill-lint: {n} skill(s) checked; "
        "every instructed command is a mise task or allowed read-only"
    )
    return 0
