# Copyright (c) 2026 Raymond Manaloto
"""Skill lint: a SKILL.md may not instruct a command a mise task already owns.

Ray's standing directive, restated 2026-08-06 and tracked as #128: *skills call
mise tasks that wrap the python library*. Until now that lived only in prose
(`mise-tasks-only.md`, `zero-bash-logic.md`) — and this repo's own doctrine says
markdown alone is "relying on the LLM" and must never be the only layer.

**The reuse is the point, and it is why this module is ~80 lines rather than a
second implementation.** :func:`kb_setup.hook_guard.decide` already owns the
redirect table, the read-only allowlist, and the remediation wording. It is
public precisely so a gate can reach it (see its docstring). So the PreToolUse
guard and this authoring-time lint are two consumers of ONE decision function:

    runtime   — Claude issues a Bash call        -> hook_guard.run()  -> decide()
    authoring — a SKILL.md instructs a command   -> skill_lint.check() -> decide()

A redirect added to ``_REDIRECT`` is therefore enforced in both places at once.
Two tables would drift, and this repo has a filed lesson for exactly that shape
(the `_safe_lane` writer/reader divergence).

The graph named the pattern before it was built: *"Lint messages inject
remediation into agent context" enables "Enforce invariants, don't
micromanage"* (`openai_com_index_harness-engineering.md`, EXTRACTED). So a
finding prints the canonical task, never just a refusal.

**What this gate does NOT enforce, stated plainly because #128 asked for it to
be.** Ray's directive has two halves. This module covers the first — *skills
call mise tasks that wrap the python library* — because it is a checkable
property of a file. The second half — *"automate agents' work into skills to
reduce tokens instead of having agents follow step-by-step instructions"* — is
**not gateable and remains guidance**. No check can tell a skill that
delegates from one that narrates: both are markdown naming tasks, and the
difference is whether the *work* moved into the module. Pretending otherwise
would be a green gate over a property nobody measured — the failure class
`.claude/skills/kb-review/SKILL.md` § *Arm your own fixes* is about: a check
must declare what it cannot see. The second half is tracked as a build
(#219, the distiller), not as a check.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from kb_setup import hook_guard
from kb_setup.result import Err, Ok, Rc, Result, exit_code

if TYPE_CHECKING:  # pragma: no cover - typing only
    from collections.abc import Callable, Iterator

# One SKILL.md per skill directory. Nested reference/*.md are prose ABOUT the
# workflow, not the instruction surface an agent follows, so they are out of
# scope until one is shown to instruct a command.
#: BOTH skill trees, and the second one is the fix. `.agents/skills/` is a
#: near-copy of `.claude/skills/` for the non-Claude lanes, it is TRACKED, and it
#: was matched by no gate at all — so a doctrine contradiction could land there
#: green. It already had: `clear-prep`'s copy tells the reader to edit a root
#: `AGENTS.md`, a file this repo deliberately does not have.
#:
#: A single string became a tuple rather than growing a brace pattern, because
#: `Path.glob` does not support `{a,b}` — it would have matched nothing and read
#: as "no findings".
DEFAULT_SKILL_GLOBS = (".claude/skills/*/SKILL.md", ".agents/skills/*/SKILL.md")

# Installer-generated by `graphify install --project` and regenerated wholesale
# by `mise run kb-skill-refresh` — not ours to author, so not ours to gate. Same
# carve-out, same reason, as `md_budget.DEFAULT_EXCLUDED_PREFIXES`.
#
# `.agents/skills/graphify/` is excluded for a DIFFERENT reason worth keeping
# straight: it is not a copy of the installer tree at all but a short hand-written
# codex stub (`skill_refresh._CODEX_SKILL`), regenerated the same way. Same
# disposition, different provenance.
DEFAULT_EXCLUDED_PREFIXES = (".claude/skills/graphify/", ".agents/skills/graphify/")

# A CommonMark fence: 3+ backticks OR 3+ tildes, then an optional info string.
# Both spellings render identically on GitHub, and recognising only backticks
# let `~~~bash` bypass the gate entirely (cold lane on c20d982, P2).
_FENCE = re.compile(r"^\s*(?P<marker>`{3,}|~{3,})\s*(?P<info>\S*)")

# The info strings that mark a block executable. A skill's prose and its
# JSON/markdown samples are not instructions; only shell fences are.
_SHELL_INFO = frozenset({"bash", "sh", "shell", "console", "zsh"})

# A placeholder line is documentation of a shape, not an instruction to run it.
# `<...>` and `$VAR`-only lines are templates; a leading `#` is a comment.
_PLACEHOLDER_ONLY = re.compile(r"^\s*(#|$)")


@dataclass(frozen=True)
class Finding:
    """One command in one SKILL.md that a mise task already owns."""

    path: str
    line: int
    command: str
    remedy: str


@dataclass(frozen=True)
class Report:
    """The result of one lint run. ``failed`` is the gate's only question."""

    findings: tuple[Finding, ...]
    scanned: tuple[str, ...]
    #: Skills whose `.claude/` and `.agents/` copies disagree — see `mirror_drift`.
    #: Carried in the REPORT rather than computed by the renderer, because the
    #: renderer must not invent an exit code: `skill_lint_main` is asserted equal
    #: to `exit_code(check_skill_lint(...))`, and a second rc decided downstream
    #: breaks the single-conversion property that assertion exists to protect.
    drift: tuple[str, ...] = ()

    @property
    def failed(self) -> bool:
        """True when a SKILL.md instructs a command a mise task owns, or a mirror drifted."""
        return bool(self.findings or self.drift)


def command_lines(raw: str) -> Iterator[tuple[int, str]]:
    """Yield ``(1-indexed line number, command)`` for each instructed command.

    Only lines inside a shell-marked fence count. A skill that *mentions*
    ``graphify query`` in prose is describing the tool, not telling an agent to
    run it — flagging that would make the gate fire on its own documentation,
    which is how a gate loses its readers.
    """
    open_marker: str | None = None
    is_shell = False
    for i, line in enumerate(raw.splitlines(), start=1):
        m = _FENCE.match(line)
        if open_marker is None:
            if m:
                open_marker = m.group("marker")
                is_shell = m.group("info").lower().split(",")[0] in _SHELL_INFO
            continue
        # CommonMark: a fence of N chars closes only on N-or-more of the SAME
        # char with NO info string. Tracking length is what stops a ```bash
        # block *inside* a ````markdown example from being read as real
        # instructions — the false positive the cold lane constructed, and one
        # a SKILL.md documenting this very gate would hit.
        if (
            m
            and m.group("marker")[0] == open_marker[0]
            and len(m.group("marker")) >= len(open_marker)
            and not m.group("info")
        ):
            open_marker = None
            is_shell = False
            continue
        if is_shell and not _PLACEHOLDER_ONLY.match(line):
            yield i, line.strip()


def check(
    root: Path,
    *,
    globs: tuple[str, ...] = DEFAULT_SKILL_GLOBS,
    exclude: tuple[str, ...] = DEFAULT_EXCLUDED_PREFIXES,
    decide: Callable[[str], str | None] = hook_guard.decide,
) -> Report:
    """Lint every SKILL.md under ``root`` for commands a mise task owns.

    ``decide`` is injected rather than imported at the call site so a caller can
    gate a different command family without forking this walker, and so a test
    can drive the FAIL direction without depending on graphify's redirect table
    staying the shape it is today.
    """
    findings: list[Finding] = []
    scanned: list[str] = []
    # Sorted across ALL globs, not per glob, so the report reads in one path
    # order rather than tree-by-tree — a mirrored pair sits adjacent.
    for path in sorted({p for pattern in globs for p in root.glob(pattern)}):
        rel = path.relative_to(root).as_posix()
        if rel.startswith(exclude):
            continue
        scanned.append(rel)
        raw = path.read_text(encoding="utf-8")
        for lineno, command in command_lines(raw):
            remedy = decide(command)
            if remedy:
                findings.append(Finding(rel, lineno, command, remedy))
    return Report(tuple(findings), tuple(scanned), mirror_drift(root))


def check_skill_lint(root: Path) -> Result[Report]:
    """The boundary (§2 R5): the lint report, or `Err` when the gate never ran.

    Returns rather than raises, and prints nothing — :func:`skill_lint_main`
    renders. Same split as ``check.check``/``check.main``, which is ``ruff``'s
    ``pub fn run(..) -> Result<ExitStatus>`` (``crates/ruff/src/lib.rs:128``).

    **This is the first converted module with a real `Err`**, and it is worth
    saying why, because the two non-zero cases here look alike and are not:

    * *Findings* — a SKILL.md instructs a command a mise task owns. The gate
      ran and did its job, so this is ``Ok(report, rc=Rc.FINDINGS)``.
    * *Nothing scanned* — the glob matched no skill at all. The gate never
      asked the question, which by ``probes-need-a-control-arm.md`` is not a
      pass and is not a finding either. That is ``Err(..., rc=Rc.NOT_RUN)``,
      and it is precisely the case the fourth ``Rc`` member was ruled for:
      neither 1 ("we looked and found something" — we did not look) nor 2
      ("you asked wrong" — the request was fine).

    The integer is unchanged in both cases, so hk fails this step exactly as
    before; what the split adds is that a caller can now tell the two apart
    without re-deriving the meaning of a bare non-zero int.
    """
    report = check(root)
    if not report.scanned:
        return Err(
            f"NO SKILLS MATCHED {DEFAULT_SKILL_GLOBS!r} — the gate did not run. "
            "Check the glob before reading this as clean.",
            rc=Rc.NOT_RUN,
        )
    return Ok(report, rc=Rc.FINDINGS if report.failed else Rc.OK)


#: Where the two skill trees live. `.claude/` is authoritative: it is the tree
#: Claude Code loads and the one every rule and task names, so a divergence is
#: repaired by copying it onto the mirror, never the other way.
_CLAUDE_SKILLS = Path(".claude/skills")
_AGENT_SKILLS = Path(".agents/skills")


def mirror_drift(root: Path) -> tuple[str, ...]:
    """Return one line per skill whose two tracked copies disagree.

    `.agents/skills/` exists so the non-Claude lanes read the same instructions.
    Nothing kept them the same, and they had already diverged where it matters
    most: `clear-prep`'s copy tells the reader to edit a root `AGENTS.md`, which
    this repo deliberately does not have — so the mirror instructs an edit to a
    file that is not there, and no gate could see it.

    BYTE-EXACT, deliberately. A "close enough" comparison would need a rule for
    which differences are allowed, and the only difference anyone has actually
    wanted — a vendor's filename — is precisely the one that was wrong. If a lane
    genuinely needs different text, it needs its own skill, the way
    `.agents/skills/graphify/` already is.

    `graphify` is skipped on both sides for that reason: the two are not copies
    at all. The `.claude/` one is graphify's >700-line installer output; the
    `.agents/` one is the short stub in `skill_refresh._CODEX_SKILL`.

    An ABSENT `.agents/skills/` tree reports nothing, because a repo that keeps no
    mirror has no mirror to be out of sync — this checks faithfulness, not
    adoption. That is a real hole and it is closed one level up instead:
    `test_this_repo_mirrors_every_skill` pins that the tree exists here with a
    copy of every skill, so deleting it fails rather than silencing the gate.
    """
    if not (root / _AGENT_SKILLS).is_dir():
        return ()
    drift: list[str] = []
    for source in sorted((root / _CLAUDE_SKILLS).glob("*/SKILL.md")):
        name = source.parent.name
        if f"{_CLAUDE_SKILLS.as_posix()}/{name}/".startswith(DEFAULT_EXCLUDED_PREFIXES):
            continue
        mirror = root / _AGENT_SKILLS / name / "SKILL.md"
        if not mirror.is_file():
            drift.append(f"{name}: no mirror at {_AGENT_SKILLS / name / 'SKILL.md'}")
        elif mirror.read_bytes() != source.read_bytes():
            drift.append(f"{name}: {_CLAUDE_SKILLS / name / 'SKILL.md'} and its mirror differ")
    return tuple(drift)


def skill_lint_main(root: Path) -> int:
    """CLI entry: print the report, `Rc.FINDINGS` on a finding, `Rc.NOT_RUN` on none scanned.

    Kept returning ``int``: ``cli.py``, the ``skill_lint`` hk step and this
    module's existing exit-code assertions are the regression arm proving the
    ``Result`` split changed no behaviour.
    """
    result = check_skill_lint(root)
    # Narrowed on `Ok`, not on `Err`: the declared return is `Result[Report]`,
    # whose third variant is `External`. Testing for `Err` leaves `Ok | External`
    # and `External` carries no `.value` — ty catches it, and narrowing the
    # POSITIVE way keeps the renderer correct if this boundary ever grows a
    # passthrough variant.
    if not isinstance(result, Ok):
        print(f"skill-lint: {result.message}")
        return exit_code(result)
    report = result.value
    for f in report.findings:
        print(f"skill-lint: {f.path}:{f.line}: {f.command}")
        print(f"            {f.remedy}")
    n = len(report.scanned)
    # `report.findings`, not `report.failed` — `failed` now also covers mirror
    # drift, and reporting "0 finding(s)" for a drift-only run would name the
    # wrong defect while the real one prints below it.
    if report.findings:
        print(
            f"skill-lint: {len(report.findings)} finding(s) across {n} skill(s). "
            "A SKILL.md instructs a command a mise task already owns; skills call "
            "mise tasks that wrap the python library (#128)."
        )
    else:
        print(
            f"skill-lint: {n} skill(s) checked; "
            "every instructed command is a mise task or allowed read-only"
        )
    for line in report.drift:
        print(f"skill-lint: mirror drift: {line}")
    if report.drift:
        print(
            f"skill-lint: {len(report.drift)} skill(s) differ between .claude/skills/ "
            "and .agents/skills/. `.claude/` is authoritative — copy it onto the "
            "mirror. A lane that needs different text needs its own skill."
        )
    return exit_code(result)
